### ISSUE TITLE
rportd - Centos 7 glibc 2.28

### ISSUE THREAD

**Issue by ukedk** [cloudradar-monitoring/rport#211]
Dear rport team
i read about rport in linux magazine and wanted to run it under centos 7. unfortunately i got the error. 

/rportd: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./rportd)

Upgrading glibc seems to be difficult.

Compiling it myself ran into the following error:

go test -v ./...
go: github.com/golang-migrate/migrate/v4@v4.14.1 requires
	github.com/docker/docker@v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible: invalid pseudo-version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/248eb0d137df81736f6c84eff5e00bf5cccc915e2a34175acacd42218fa12c7f: exit status 128:
	fatal: git fetch-pack: expected shallow list
make: *** [test] Error 1

Is there a possibility to run it on centos 7 ?
Do you plan to provide a docker image of rportd ?

Thanks & Many greetings
Ulrich

**Comment by thorstenkramm** [comment]
Hi Ulrich.
Why not use the binaries we provide?
They run flawlessly on CentOS.
https://github.com/cloudradar-monitoring/rport/releases
Cheers
Thorsten

**Comment by ukedk** [comment]
@thorstenkramm I would like to ;) Unfortunately the binary (tested with rport_0.1.31_Linux_x86_64.tar.gz) needs >= glibc 2.28 ; Centos 7 uses glibc 2.17 ...maybe someone will have mercy ;)

**Comment by thorstenkramm** [comment]
@ukedk You are right.
```
[root@qa-lin-centos7 ~]# ./rportd -version
./rportd: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./rportd)
``` 
The reason is that on compiling we need the sqlite c libraries and a c compiler. 
We will try to change the build workflow to use some older linux instead of the latest Ubuntu. 
CentOS 7 comes with glibc-2.17. 
Even Ubuntu 16.04 has a newer version (2.23). We will try our best.

**Comment by ukedk** [comment]
@thorstenkramm thank you! Would be very nice if you can make it work.

**Comment by m-terel** [comment]
Hi, @ukedk

We'll try to provide binaries for centos 7. Meanwhile, you can try to build it from the sources.

I've tried to do it on centos 7. It works ok for me. Please tell me what **go version** are you using? Please try to upgrade it and try again.

This is on my machine:
```
# uname -a
Linux mt-centos7-6-io 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
# go version
go version go1.16.4 linux/amd64
```
```
# git --version
git version 1.8.3.1
```
```
# ldd --version
ldd (GNU libc) 2.17
```
```
# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
```

Hope it helps :)

**Comment by m-terel** [comment]
@ukedk please try to use binaries from a new release https://github.com/cloudradar-monitoring/rport/releases/tag/0.1.32 and let us know if you have any issues.

**Comment by ukedk** [comment]
@m-terel Thank you very much! reportd is starting without issues.
