### ISSUE TITLE
rportd : Constant disk writes

### ISSUE THREAD

**Issue by Gouar** [cloudradar-monitoring/rport#229]
Hi,
I'm having constant disk writes on small VM hosted on Azure.
The more I add clients, the more it increases (currently 21 connected).
![image](https://user-images.githubusercontent.com/13763507/119692616-d75db780-be4b-11eb-9f7c-89b44a5e3401.png)

Specs:
rportd 0.1.30
Ubuntu 20.04 VM on Azure (1 vCPU, 0.5 GB ram)

**Comment by thorstenkramm** [comment]
Hi Gouar,

The state of each client is constantly updated in the internal sqlite database. 
But I admit the write-load you are obbserving is beyond the normal. We have reproduced this behavior on our servers and we are working on a fix.
Thanks for reporting.

**Comment by m-terel** [comment]
@Gouar we've fixed the issue. Please try to use binaries starting from https://github.com/cloudradar-monitoring/rport/releases/tag/0.1.34 and please let us know if you have any issues.

**Comment by Gouar** [comment]
Problem solved, thank you.
