### ISSUE TITLE
during installation, error 422 curl

### ISSUE THREAD

**Issue by cayenne17** [cloudradar-monitoring/rport#322]
Hello,
I am testing the rport software.
During the execution of the install script on Debian 10, I have the following error message that appears before the install script finishes :
`curl: (22) The requested URL returned error: 422`

![image](https://user-images.githubusercontent.com/47927025/138179500-d213b051-bc82-4f8a-afc3-4e655016925a.png)

**Comment by thorstenkramm** [comment]
@MasterKishin The automated installer scripts starts the rport server API on port 443. The assign an FQDN the DNS service requires, rport is running on 443. That FQDN is then used to create the certs via let's encrypt using the built-in web server of certbot.
If you want to run the rport server API on port 3000 you must create your own FQDN and then created the certificates either by self-singing or using let's encrypt manually. 
If you run the installer using all defaults –https on port 443– , your server comes up with an FQDN and a valid SSL certificated. If you change the https port from 443 to something else after the installation, the DNS record will be deleted after 24 hours. 
I don't see a good reason for not running the API on port 443 if the port is available. If you run a web server on a public IP address, any port will be scanned sooner or later. Using none-standard ports is not a security measure to hide a service. (If that was your idea.) But as mentioned. You are free to use any port you like – but not with the automated installer script.

**Comment by MasterKishin** [comment]
@thorstenkramm Looking at the conversation, my comments might not have been clear. I was following the instructions here:

https://kb.rport.io/install-the-rport-server/install-rport-on-any-virgin-cloud-vm

The VM I was running the script on resides on a public cloud, I have a public IP and isn't behind a NAT. No firewalls in between and no iptables or other firewall daemon configured on the VM (a Debian Buster install as per the docs).

The script still fails at line 133 because the curl command returns a HTTP/422 error:

`PUBLIC_DNS=$(curl -fSs https://freedns.rport.io -F create=random)`

The nature of the failure at line 133 causes the script to exit. If the script were still running, it would then check for a null value of $PUBLIC_DNS, write the error message to stdout, and then return false.

```
[!] Creating an FQDN for your RPort server failed.
    Go to https://rport.io/en/contact and ask for help.
```

Here's some info on what a HTTP/422 error is:
https://www.keycdn.com/support/422-unprocessable-entity

My guess is that there is a problem with the MIME data specified when posting to freedns.rport.io, maybe create=random is no longer valid? Either way, this issue is still an issue.

**Comment by thorstenkramm** [comment]
@MasterKishin Freedns.rport.io returns a more verbose error.
Replace 
`PUBLIC_DNS=$(curl -fSs https://freedns.rport.io -F create=random)` 
by 
```
PUBLIC_DNS=$(curl -Ss https://freedns.rport.io -F create=random)
echo $PUBLIC_DNS
```
remove the `-f` and print the result of the request to the console.

Maybe this brings some useful hints.
Does your server respond to ICMP echo requests?

**Comment by cayenne17** [comment]
> @MasterKishin Freedns.rport.io returns a more verbose error. Replace `PUBLIC_DNS=$(curl -fSs https://freedns.rport.io -F create=random)` by
> 
> ```
> PUBLIC_DNS=$(curl -Ss https://freedns.rport.io -F create=random)
> echo $PUBLIC_DNS
> ```
> 
> remove the `-f` and print the result of the request to the console.
> 
> Maybe this brings some useful hints. Does your server respond to ICMP echo requests?

Hello, 
I just tested: 
```
PUBLIC_DNS=$(curl -Ss https://freedns.rport.io -F create=random)
echo $PUBLIC_DNS
```
it puts this error message :
Host 82.64.xx.xx not alive or blocks pings


I just accepted ICMP on my router and that solves the problem.
It is necessary to add in the documentation that the server or the router in front must answer the ICMP ping

**Comment by thorstenkramm** [comment]
@MasterKishin I'm glad it's working now. 
We will improve the installer, so it will bring up the server with a self-signed certificate first and the let's encrypt certificate is optional. If it fails, the server is still usable.

**Comment by cayenne17** [comment]
> @MasterKishin I'm glad it's working now. We will improve the installer, so it will bring up the server with a self-signed certificate first and the let's encrypt certificate is optional. If it fails, the server is still usable.

En faite, pour que freedns.rport.io ne face pas d'erreur 422, il faut absolument que l'IP frontal d'internet réponde au ping ICMP. 
Le port 443 n'a pas besoin d'être ouvert.

**Comment by MasterKishin** [comment]
@thorstenkramm @cayenne17 good find, I did some more troubleshooting of the curl command a couple of nights ago and looked for the errors that way.

So long as the documentation reflects that ICMP is required for the cloud installer to work, this should suffice to remedy this issue. Graceful failover from the curl command would be ideal, but you can add this to the documentation in the interim.

My testing VM was an AWS Lightsail instance, which has ICMP blocked by default. Once I allowed ICMP through the firewall (not iptables, each Lightsail instance has a perimeter firewall) the subdomain was generated.

**Comment by MasterKishin** [comment]
> > @MasterKishin I'm glad it's working now. We will improve the installer, so it will bring up the server with a self-signed certificate first and the let's encrypt certificate is optional. If it fails, the server is still usable.
> 
> In fact, in order for freedns.rport.io not to face a 422 error, it is absolutely necessary that the Internet front-end IP responds to the ICMP ping. Port 443 does not need to be open.

@cayenne17 true, though port 80 does need to be open so the http challenge for the SSL certs can complete.
