### ISSUE TITLE
Feature Request: Add OTP + Remember device option

### ISSUE THREAD

**Issue by Evo-c** [cloudradar-monitoring/rport#325]
Would be really useful to use OTP instead of being emailed a code if possible. Also as the timeout is quite short at the moment would it be possible to add either a checkbox at login to remember the device for either 7,14 or 30 days or if not maybe an entry in the config file to specify the session expiry time?

Thanks for creating RPORT, big fan I use it daily!

**Comment by thorstenkramm** [comment]
@Evo-c OTP is now included in 0.5.0 
https://oss.rport.io/docs/no02-api-auth.html#enabling-2fa-with-an-authenticator-app-totp-auth
