### ISSUE TITLE
Frontend - Inconsistent when adding new tunnel

### ISSUE THREAD

**Issue by vaporup** [cloudradar-monitoring/rport#339]
```
   rport: 0.4.5
  rportd: 0.4.5
frontend: rport-frontend-stable-0.4.1-build-731 
```

Hi,

I have a test server running
and establish 2 tunnels directly when connecting

```
rport --data-dir=/tmp/rportc --auth clientAuth1:1234 192.168.30.166:8080 25001:0.0.0.0:22 25002:0.0.0.0:22
```

![rport-1](https://user-images.githubusercontent.com/2084128/139749409-671df1e9-3eda-4c97-8042-a7b1d144ee10.png)

If I want to add a third one with "No Restrictions" I get the message  
that a similar tunnel already exists.

![rport-2](https://user-images.githubusercontent.com/2084128/139749413-530938c5-0482-4fc7-a830-c1fdc23da395.png)

But if I set the ACL to a network range which has the same effect, it works.

![rport-3](https://user-images.githubusercontent.com/2084128/139749415-1ebec21b-41ba-4e39-9b8a-8aa624f847c9.png)
![rport-4](https://user-images.githubusercontent.com/2084128/139749418-8a527bab-f3aa-4016-aa91-6d5b6f819002.png)

Also notice the green security icon which now says "Protected Tunnel"

Checking the API and the rportcli the tunnels differ only on the ACL value

### API

```
      "tunnels": [
        {
          "lhost": "0.0.0.0",
          "lport": "25001",
          "rhost": "0.0.0.0",
          "rport": "22",
          "lport_random": false,
          "scheme": null,
          "acl": null,
          "idle_timeout_minutes": 0,
          "id": "1"
        },
        {
          "lhost": "0.0.0.0",
          "lport": "25002",
          "rhost": "0.0.0.0",
          "rport": "22",
          "lport_random": false,
          "scheme": null,
          "acl": null,
          "idle_timeout_minutes": 0,
          "id": "2"
        },
        {
          "lhost": "0.0.0.0",
          "lport": "24397",
          "rhost": "0.0.0.0",
          "rport": "22",
          "lport_random": true,
          "scheme": "ssh",
          "acl": "0.0.0.0",
          "idle_timeout_minutes": 5,
          "id": "8"
        }
      ]
```

### rportcli ( ID shortened )

```
Tunnels
ID CLIENT ID CLIENT NAME LOCAL HOST LOCAL PORT REMOTE HOST REMOTE PORT LOCAL PORT RAND SCHEME ACL     
1  3f68792f             0.0.0.0    25001      0.0.0.0     22          false                          
2  3f68792f             0.0.0.0    25002      0.0.0.0     22          false                          
9  3f68792f             0.0.0.0    25003      0.0.0.0     22          false            ssh     0.0.0.0 
```

**Comment by thorstenkramm** [comment]
@vaporup Duplicated tunnels are identified by comparing json objects. There is no logic to recognize that an ALC of 0.0.0.0 effectively means no ACL. I'll add an improvement to our backlog.
Rejecting 0.0.0.0 as an invalid input for the ACL on the frontend is a quick fix we will add almost immediately.
Thanks for your collaboration.

**Comment by vaporup** [comment]
Well, it is not an duplicate tunnel.
I think it should be possible to create another tunnel to the same destination but with a different exposed port
which works by using a "Specific network range" instead of "No restrictions"

**Comment by thorstenkramm** [comment]
@vaporup Creating two or more tunnels to the same target port is possible.
![image](https://user-images.githubusercontent.com/16852023/140038524-3b618269-4d45-4bfa-860f-69d3c0f6cf54.png)

But it's not possible to create two tunnels with either the same ACL or without ACL. Why should someone do this?

**Comment by vaporup** [comment]
The first 2 tunnels were created by the rport client. The third one I wanted to create via frontend with a different exposed port (specific port 25003) which was not allowed to create

**Comment by rafalf** [comment]
@thorstenkramm @vaporup 

rejecting 0.0.0.0 is fixed and verified in rport-frontend-development-20211110-build-769

I believe I've reproduced the other issue with adding 3rd tunnel, its a backend issue - we're on it 

Closing it as we have a ticket to address this issue
