### ISSUE TITLE
Frontend - Tags not readable in Dark Mode in Inventory Table

### ISSUE THREAD

**Issue by vaporup** [cloudradar-monitoring/rport#340]
```
   rport: 0.4.5
  rportd: 0.4.5
frontend: rport-frontend-stable-0.4.1-build-731 
```

### Dark Mode - Clients (OK)

![frontend-clients-dark-mode](https://user-images.githubusercontent.com/2084128/139753965-18eaf006-b1b7-4bf4-b99e-2a2fde83cac4.png)

### Default Mode - Clients  (OK)

![frontend-clients-default-mode](https://user-images.githubusercontent.com/2084128/139753966-d428c905-fb2a-4d5a-95f7-037a6b355b62.png)

### Dark Mode - Inventory  (**Tags not readable**)

![frontend-inventory-dark-mode](https://user-images.githubusercontent.com/2084128/139753967-0de5c884-9b94-4a6c-8afb-fc8ff6629799.png)

### Default Mode - Inventory  (OK)

![frontend-inventory-default-mode](https://user-images.githubusercontent.com/2084128/139753968-b6e70fbe-8df5-4827-ad87-954b305f0749.png)

**Comment by thorstenkramm** [comment]
@vaporup Thank you for reporting. This helps us a lot. We will fix it soon.

**Comment by rafalf** [comment]
verified in rport-frontend-development-20211110-build-767
