### ISSUE TITLE
Feature Request: Frontend - Overview Tunnel List

### ISSUE THREAD

**Issue by vaporup** [cloudradar-monitoring/rport#341]
```
   rport: 0.4.5
  rportd: 0.4.5
frontend: rport-frontend-stable-0.4.1-build-731 
```

Maybe I have overlooked it, but I didn't find an easy overview like the one from rportcli

```
rportcli tunnel list
```

gives a nice overview of all established tunnels

```
Tunnels
ID CLIENT ID CLIENT NAME LOCAL HOST LOCAL PORT REMOTE HOST REMOTE PORT LOCAL PORT RAND SCHEME ACL 
1  client1               0.0.0.0    25001      0.0.0.0     22          false                      
2  client1               0.0.0.0    25002      0.0.0.0     22          false                      
1  client2               0.0.0.0    25004      0.0.0.0     3389        false    
```
Something similar in the web frontend would be nice

**Comment by thorstenkramm** [comment]
Implemented in 0.6.0.

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/16852023/159231045-bf837e4b-872e-4fa2-8cfd-56525fbf43ca.png">

Swagger docu for the new API endpoint [/tunnels](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/cloudradar-monitoring/rport/master/api-doc.yml#/Clients%20and%20Tunnels/get_tunnels)
