### ISSUE TITLE
Feature Request: Pair client with direct link to server

### ISSUE THREAD

**Issue by UncleSamSwiss** [cloudradar-monitoring/rport#364]
Currently the easiest way to install the rport client on a new system is by downloading the bootstrapper from an URL like this: `https://pairing.rport.io/AbCdE`.

It would be great to be able to use the rport server we already have and just use a URL like `https://abcdefghijkl.users.rport.io/pairing/AbCdE` (of course it wouldn't have to be a `rport.io` domain at all).

This would allow to pair a new device even if the official rport server is unreachable (e.g. in an environment with very limited access to the "outside world").

**Comment by thorstenkramm** [comment]
@UncleSamSwiss I understand your requirement.
The reason why we have it separated is that the pairing service and the generated installer scripts are under constant development too. Merging the paring scripts into the main repository is possible but not convenient for our team and workflows. But I keep your request in mind. Maybe we can source it in on release creation.

You can also try this workaround.
Generate a pairing code as usual and then do the following on your rport server.
```bash
CODE=EcY5dc
mkdir /var/lib/rport/docroot/pairing
mkdir /var/lib/rport/docroot/pairing/windows
mkdir /var/lib/rport/docroot/pairing/linux
curl -o /var/lib/rport/docroot/pairing/linux/$CODE https://pairing.rport.io/$CODE
curl -A "Windows NT WindowsPowerShell/5.0" -o /var/lib/rport/docroot/pairing/windows/$CODE https://pairing.rport.io/$CODE
```

This gives you at least some static paring scripts which clients can use without full internet access.

**Comment by UncleSamSwiss** [comment]
Thanks for you clarification. We will find a way around this.
