### ISSUE TITLE
Feature Request: Client Pairing via API

### ISSUE THREAD

**Issue by Turbobommel** [cloudradar-monitoring/rport#370]
Hello,

is it possible to trigger a Client Installation and Pairing via API?
We'ld like to deploy rport via Software Deployment.

If I misunderstood the documentation and its already in, I am sorry.

Thanks!

**Comment by thorstenkramm** [comment]
The client installation does not require any action on the server. The clients auto-register.
You can download the pairing script once and re-use it on all your machines. It contains the hostname of your server and all other needed details. 
Alternatively, you can download the pairing script and rewrite the steps with Ansible or Salt.
