### ISSUE TITLE
Corrupted file - rport_0.5.0_Linux_mipsle_softfloat.tar.gz 

### ISSUE THREAD

**Issue by qraleq** [cloudradar-monitoring/rport#381]
Hi, 

I'm having problems with downloading and untarring `rport_0.5.0_Linux_mipsle_softfloat.tar.gz`. When I try to curl this file I get 
`curl: (23) Failed writing body (2240 != 16384)`. 

It seems that the archive is corrupt. Can you please check if you observe the same problem?

**Comment by thorstenkramm** [comment]
@qraleq I cannot confirm there is an issue with the download.
```
$ curl -LOSs https://github.com/cloudradar-monitoring/rport/releases/download/0.5.0/rport_0.5.0_Linux_mipsle_softfloat.tar.gz
$ tar tzf rport_0.5.0_Linux_mipsle_softfloat.tar.gz
rport.example.conf
rport
$ tar xzf rport_0.5.0_Linux_mipsle_softfloat.tar.gz rport
$ file rport
rport: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, Go BuildID=h_b3WSI1rW5dW_ahFX0F/MHMTe_eyGKTTDp6Oxd8K/jnyLLZQxShdVnZznr7My/ptocXB1n_Mf0-N7vmT73, stripped
```

Note the `-L` option of curl. The links published on the release page of GitHub lead to a redirect to the real location of the files. If curl does not follow redirects, you will download an HTML file with the new URL.
`wget` follows redirects by default.
