### ISSUE TITLE
rport linux client monitoring 

### ISSUE THREAD

**Issue by senhakan** [cloudradar-monitoring/rport#390]
I'm getting the following error in logfile when I run rport client on "centos 7.7" client.  is there a package that the client application depends on?

Error comes in vaguely but sends cpu info

client: Could not get cpu information:
client: Update status refresh failed: no supported package manager found

**Comment by thorstenkramm** [comment]
@senhakan This is a known error that has already been fixed in version [0.5.2](https://github.com/cloudradar-monitoring/rport/releases/tag/0.5.2). It's a false alert. You can either safely ignore the error or update to 0.5.2.
0.5.2 is compatible with all 0.5.x frontend versions.
