### ISSUE TITLE
monitoring.db using all disk space

### ISSUE THREAD

**Issue by diegomontoya** [cloudradar-monitoring/rport#396]
Using latest stable 0.5.0 release and monitoring.db is now consuming all disk space of a small VM.

```
-rw-r--r--  1 rport rport  20K Dec 23 04:28 api_sessions.db
-rw-r--r--  1 rport rport 456K Dec 19 09:32 auditlog.db
-rw-r--r--  1 rport rport  16K Dec 16 03:02 client_groups.db
-rw-r--r--  1 rport rport 224K Dec 23 04:30 clients.db
-rw-r--r--  1 rport rport 2.0M Dec 19 09:32 jobs.db
-rw-r--r--  1 rport rport  44K Oct 15 21:36 library.db
-rw-r--r--  1 rport rport  21G Dec 23 04:27 monitoring.db
-rw-r--r--  1 rport rport  32K Dec 23 04:30 monitoring.db-shm
-rw-r--r--  1 rport rport 4.7M Dec 23 04:30 monitoring.db-wal
-rw-rw-r--  1 rport rport   47 Dec 23 04:27 rportd-fingerprint.txt
-rw-r--r--  1 rport rport  36K Oct 16 20:13 vault.sqlite.db
```

**Comment by senhakan** [comment]
I have the same problem, I changed the data_storage_days parameter in rportd.conf. but neither the number of records nor the size decreased

**Comment by thorstenkramm** [comment]
@diegomontoya @senhakan 
You must reduce the data storage days in the [rportd.conf ](https://github.com/cloudradar-monitoring/rport/blob/master/rportd.example.conf#L355). This prevents the file from growing, but it doesn't reduce the size of an existing file. 
After changing the setting, stop the rport server, delete the `monitoring.db*` files, and start rportd again. A new file will be created automatically.

**Comment by diegomontoya** [comment]
We have 29 servers registered with rport and in exactly 12 days time used up 25GB of data using default 30 day data retention. I really believe the default should be reduced to 7 days. Rport can literally eat all disk space in a matter of days using small cloud VMs.
