### ISSUE TITLE
Getting "dial tcp XXXXXXX:8080: connect: connection refused" on fresh rport 5 install on Ubuntu 20.04

### ISSUE THREAD

**Issue by Palezvar** [cloudradar-monitoring/rport#406]
Hello folks:

I followed the instructions on https://oss.rport.io/docs/#install-the-server. I had to change a couple of steps because the tar file had to rportd binary in it. Instead it had rport. Same thing for the config file. 

This is a brand new ubuntu 20.04 LTS on VMware. Rport >> rport_0.5.0_Linux_x86_64.tar.gz.

Firewall is disabled on the server. I created a key using "openssl rand -hex 18" command as well. Even though I did not see a line called "key_seed" in the config file I added it manually and pasted the key I created. I am not sure if this is the fingerprint. Like the following:

```
[client]
## rportd server address.
## Mandatory IP address and port divided by a colon.
server = "10.10.10.202:8080"
key_seed = "XXXXXXXXXXXXXXXXXXXXXXX"
```

When I start the server: rport -c /etc/rport/rport.conf --log-level info &

This is what I see in the log files:
2022/01/03 20:31:45 client: Retrying in 1.6s...
2022/01/03 20:31:47 client: Connecting to ws://10.10.10.202:8080
2022/01/03 20:31:47 client: dial tcp 10.10.10.202:8080: connect: connection refused
2022/01/03 20:31:47 client: Connection error: dial tcp 10.10.10.202:8080: connect: connection refused (Attempt: 5)
2022/01/03 20:31:47 client: Retrying in 3.2s...
2022/01/03 20:31:50 client: Connecting to ws://10.10.10.202:8080
2022/01/03 20:31:50 client: dial tcp 10.10.10.202:8080: connect: connection refused
2022/01/03 20:31:50 client: Connection error: dial tcp 10.10.10.202:8080: connect: connection refused (Attempt: 6)
2022/01/03 20:31:50 client: Retrying in 6.4s...
2022/01/03 20:31:54 client: Update status refreshed, 43 updates available (0 security)
2022/01/03 20:31:56 client: Connecting to ws://10.10.10.202:8080
2022/01/03 20:31:56 client: dial tcp 10.10.10.202:8080: connect: connection refused
2022/01/03 20:31:56 client: Connection error: dial tcp 10.10.10.202:8080: connect: connection refused (Attempt: 7)
2022/01/03 20:31:56 client: Retrying in 12.8s...

Am I missing something?

Thanks

**Comment by Palezvar** [comment]
Firewall status:

```
root@rport:~# ufw status
Status: inactive
root@rport:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
root@rport:~#
```

**Comment by Palezvar** [comment]
I suppose I should not have only copied and pasted the instructions on the web site. I noticed there is a typo in the instructions on "https://oss.rport.io/docs/#install-the-server"... The download links are pointing to rport client instead of server.

Closing this issue.

**Comment by thorstenkramm** [comment]
@Palezvar Thank you for the hint. I changed the link to the correct one.
