### ISSUE TITLE
Debian 11: Installation not possible

### ISSUE THREAD

**Issue by MalteKiefer** [cloudradar-monitoring/rport#407]
Hello,

try to install the rport client on a Debian Linux 11 Server:

```bash
root@server:/tmp# sudo sh rport-installer.sh -x -s -i
Installing rport client
Detected Linux Distribution: Debian GNU/Linux 11 (bullseye)
Success: rmm.intellytec.de:80 is reachable. All good.
Success: rport installed to /usr/local/bin/rport
Success: /etc/rport/rport.conf created.
Preparing /etc/rport/rport.conf
Success: RPort will run as user rport
Installing systemd service for rport
Service installed
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
rport.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rport
A /etc/sudoers.d/rport-update-status has been created. Please review and change to your needs.
A /etc/sudoers.d/rport-all-cmd has been created. Please review and change to your needs.
tacoscript
Tacoscript installed taco version Version: 0.2.0
Build time: 2021-12-07T13:47:06Z
Git commit: b4afb1f8a26ae537f58f3cdfb47b45730a024c18

#
# -------------!!   ERROR  !!-------------
#
# Installation of rport finished with errors.
#

Try the following to investigate:
1) systemctl rport status

2) tail /var/log/rport/rport.log

3) Ask for help on https://kb.rport.io/need-help/request-support

root@server:/tmp# systemctl rport status
Unknown command verb rport.
```

Log does not exist.
Don't know, why I get this error.

**Comment by thorstenkramm** [comment]
@MalteKiefer The main error is caused here

> System has not been booted with systemd as init system (PID 1). Can't operate.

How did you install the system? How did you manage to have a Debian system without systemd?
The installer script can handle this edge case easily, but I need to prepare a system similar to yours without systemd.

Thanks for your collaboration.

**Comment by MalteKiefer** [comment]
Hello,

it is a root server from netcup, with their Debian 11 minimal installation image. Therefore I had little influence on the base installation. What info do you need from the system?

**Comment by MalteKiefer** [comment]
Run the script again, fixed the issue

**Comment by thorstenkramm** [comment]
@MalteKiefer Strange.
Have you installed some other software after the first rport installation that might have installed systemd as a dependency? 
Is `systemctl status rport` now working?  
I'm trying to get a Netcup Debian server to check their minimal Debian installation.

**Comment by thorstenkramm** [comment]
I created a minimal Debian11 server on Netcup. I cannot reproduce the issue. The pairing scripts runs flawlessly. My guess is: The error was produces either by a faulty provisioning of the VM or the VM has not fully loaded systemd yet.
