### ISSUE TITLE
Rport Server Memory leak 

### ISSUE THREAD

**Issue by msbusk** [cloudradar-monitoring/rport#408]
It might look like there's a memory leak. This is our installation. RAM Consumption decreases when we restart the server at night.

![image](https://user-images.githubusercontent.com/88252503/148063837-743c0d2e-e590-41e9-9c1c-0ac72bcaf249.png)

TCP: too many orphaned sockets

if we restart rportd or the server then the consumption decreases.

We are running version 5.0 - are there others out there experiencing the same problem?

**Comment by thorstenkramm** [comment]
@msbusk That's strange.
How many clients are connected?
What does `awk '{print $3*4096/(1024*1024)}'</proc/sys/net/ipv4/tcp_mem` gives you? This is the amount of memory in Mega Bytes consumed by TCP connections.

This is our test server with 350 client constantly connected.
![image](https://user-images.githubusercontent.com/16852023/148068937-d798c331-dee4-45a4-abd9-040493b94c60.png)

```
node1:~# awk '{print $3*4096/(1024*1024)}'</proc/sys/net/ipv4/tcp_mem
175.945
```

**Comment by msbusk** [comment]
We have 200 clients.

This is what I get on our: 
awk '{print $3*4096/(1024*1024)}'</proc/sys/net/ipv4/tcp_mem
359.297

**Comment by thorstenkramm** [comment]
I'll close the issue because of inactivity.
