### ISSUE TITLE
After Update I got runtime error

### ISSUE THREAD

**Issue by datazon** [cloudradar-monitoring/rport#417]
After updating from 0.4.2 to 0.5.8 I got follwing error. Clients can't establish any connections.

`2022/01/11 12:20:32 http: panic serving xxx.xxxx.xxx.xxx:7550: runtime error: invalid memory address or nil pointer dereference
goroutine 246 [running]:
net/http.(*conn).serve.func1(0xc0004c4820)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:1801 +0x147
panic(0xc1b080, 0x118a150)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:975 +0x47a
github.com/cloudradar-monitoring/rport/server/clients.(*Client).StartTunnel(0xc000289d40, 0xc00058a900, 0xc000548160, 0x11e3600, 0xc000295cc0, 0xc0003b05f0, 0x4, 0xc000247780)
        /home/runner/work/rport/rport/server/clients/client.go:123 +0x2cb
github.com/cloudradar-monitoring/rport/server.(*ClientService).startClientTunnels(0xc0000f6780, 0xc000289d40, 0xc000223740, 0x1, 0x1, 0x4, 0x0, 0x0, 0x1, 0xbe0100)
        /home/runner/work/rport/rport/server/client_service.go:320 +0x1c5
github.com/cloudradar-monitoring/rport/server.(*ClientService).StartClient(0xc0000f6780, 0xdd1ac0, 0xc0003dd180, 0xc0002c8dd0, 0x10, 0xc000028600, 0x24, 0xdd85c0, 0xc000538420, 0x1, ...)
        /home/runner/work/rport/rport/server/client_service.go:260 +0x771
github.com/cloudradar-monitoring/rport/server.(*ClientListener).handleWebsocket(0xc0001a5b30, 0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /home/runner/work/rport/rport/server/client_listener.go:252 +0x89c
github.com/cloudradar-monitoring/rport/server.(*ClientListener).handleClient(0xc0001a5b30, 0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /home/runner/work/rport/rport/server/client_listener.go:172 +0x32e
net/http.HandlerFunc.ServeHTTP(0xc0004016e0, 0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2042 +0x44
github.com/cloudradar-monitoring/rport/server/api/middleware.MaxBytes.func1(0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /home/runner/work/rport/rport/server/api/middleware/maxbytes.go:15 +0x1d4
net/http.HandlerFunc.ServeHTTP(0xc0004dd380, 0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2042 +0x44
github.com/cloudradar-monitoring/rport/share/security.RejectBannedIPs.func1(0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /home/runner/work/rport/rport/share/security/middleware.go:21 +0x133
net/http.HandlerFunc.ServeHTTP(0xc0004dd3a0, 0xdcdac0, 0xc0002d8000, 0xc00009f400)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2042 +0x44
github.com/jpillora/requestlog.WrapWith.func1(0xdcea40, 0xc00015c8c0, 0xc00009f400)
        /home/runner/go/pkg/mod/github.com/jpillora/requestlog@v1.0.0/wrap.go:80 +0x97
net/http.HandlerFunc.ServeHTTP(0xc0004dd4a0, 0xdcea40, 0xc00015c8c0, 0xc00009f400)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc00015c2a0, 0xdcea40, 0xc00015c8c0, 0xc00009f400)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0004c4820, 0xdd1ac0, 0xc000456000)
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.15.15/x64/src/net/http/server.go:2969 +0x36c`

**Comment by thorstenkramm** [comment]
@datazon 
0.5.8 is work in progress and not a stable release. Please upgrade from 0.4.2 to 0.5.0 and check again.

**Comment by thorstenkramm** [comment]
Fixed with 0.5.8
