### ISSUE TITLE
want simple API access to tunnels, but no tunnels listed?

### ISSUE THREAD

**Issue by GorillaDaddy** [cloudradar-monitoring/rport#430]
for example:

curl -s -u admin:foobaz http://localhost:3000/api/v1/clients`
`
the only response is:

```
{
  "data": [
    {
      "id": "5616a70e-81a0-4eec-bab3-0861e3c88334",
      "name": "my dev system",
      "hostname": "localhost"
    }
  ]
}
```

with no section for the open tunnels (there are two, also made via the API). One where I specified the server port and the remote port, the other where I specified only the remote port & allowed random assignment for the server.

All I want is a list of all users & their active tunnels,  the server ports that map to the remote destination ports.

**Comment by Hal9000it** [comment]
Some issue:
I follow the docs but the output is made of a little subset of fiels and is not equal to the example of the doc.
What I forgot to setup for obtaining a full report of clients/tunnels ??

**Comment by thorstenkramm** [comment]
To get the list of active tunnel you must query the `GET /tunnels` endpoint.
📖 Check the [API docs](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/cloudradar-monitoring/rport/master/api-doc.yml#/Clients%20and%20Tunnels).

**Comment by Hal9000it** [comment]
Thanks.
Anyway the document at the link is not exact. 
Thank you again
