### ISSUE TITLE
Feature Request : Monitoring cpu temperature

### ISSUE THREAD

**Issue by alhdo** [cloudradar-monitoring/rport#435]
Would be nice to be able to monitor the cpu temperature in the motoring section. On Edge device it is often useful to monitor temperature.

**Comment by thorstenkramm** [comment]
@alhdo 
Monitoring the CPU temperature is not that easy. Our company is also developing monitoring agents. On Windows, it cannot be achieved with pure Go code. DLLs must be developed or licensed from third-party vendors. 
On Linux the [lm-sensors](https://github.com/lm-sensors/lm-sensors) project and the corresponding kernel modules also does not support all sensors. 

We are planning a generic monitoring plugin API on the client. This will enable you to put any measurement data into a queue and the data becomes available on the server and the UI. 

Native temperature monitoring of CPU, fans, main board etc. will not be implemented directly in the rport client.
