### ISSUE TITLE
Feature Request : Cron job managment

### ISSUE THREAD

**Issue by alhdo** [cloudradar-monitoring/rport#438]
Would be nice to have cronjob management for linux based system and some sort of task scheduling for windows.

**Comment by thorstenkramm** [comment]
@alhdo It's underway. https://blog.rport.io/2022/02/rport-060-announced.html

**Comment by thorstenkramm** [comment]
Implemented in 0.7.0 [See documentation](https://kb.rport.io/digging-deeper/the-scheduler).
