### ISSUE TITLE
Client to receive port(s)/tunnel(s)

### ISSUE THREAD

**Issue by geoynomous** [cloudradar-monitoring/rport#445]
Currently on can configure (through https://myid.users.rport.io/dashboard, or directly in client config) a client to offer ports that are then made available on https://myid.users.rport.io (on a free port or a specific port). Love that feature for remote access.

Somehow when I read about rport I thought that there is a also a client that can **receive** ports. That is I install a client on a system, and specify that this client should offer certain remote ports on the localhost adapter.

Example: A standard rport client (say id: licenseServer) offers port 22350. Then on my local computer I start a "receiving" client (which is actually a 'server') that connects (through https://myid.users.rport.io) to the licenseServer and thus. "tunnels" port 22350 onto the localhost adapter. 

Why I think this is a good feature: 
* The rportd NEVER offers 22350 (or a free mapped one) to anyone in the public internet - even though there is a firewall that can restrict the offer to certain IP address(es)
* The receiving side can also be behind an NAT
* My specific use case is to connect to customers IoT devices - and for each of them running some listener software in a docker container - at some point there won't be enough free ports on the rportd to handle them all.

Maybe this scenario is already supported in some other way and I am just missing the right link? 

Otherwise amazing product!

**Comment by geoynomous** [comment]
Any update on this?

**Comment by thorstenkramm** [comment]
@geoynomous 
>

**Comment by thorstenkramm** [comment]
@geoynomous 

> My specific use case is to connect to customers IoT devices - and for each of them running some listener software in a docker container - at some point there won't be enough free ports on the rportd to handle them all.

This sounds strange and complicated.

The approach of rport is to create the tunnels only when needed. You will hit the limit only if you want and need to connect via tunnels e.g. over SSH to more than 65k devices concurrently. Is that really your use case?
There is no limited on connected devices. 

Furthermore, I don't understand why making a port of the server available on the client would help.

**Comment by geoynomous** [comment]
There is a client - let's call it IoT-Device-A on which port 2244 and 3355 are providing some service. I install the rport client. Then on the server I can publish these ports under a FQDN as some port 2xxxx - say 22244 and 23355. - The thing is: Now these ports are open on the public internet - even when restricted to a single IP address. I do not like to have that. 

My suggestion can actually be mitigated in another way
* Use an ACL with 127.0.0.1
* Use an SSH tunnel to the server (some account restrictions should be put in place): `ssh -L 3355:localhost:23355 rport.example.com`

I was just thinking that a "target"-client could benefit from the configuration options - like which target client can access which port of a "source"-client (aka rport client now) - maybe a target-client belongs to a user. 

Does this clarify more?

**Comment by geoynomous** [comment]
And one more thing: On the Tunnels I cannot see whether a tunnel with be closed after some inactivity or is scheduled to be destroyed (maybe a countdown for each: how much time left?),

**Comment by thorstenkramm** [comment]
@geoynomous 

> ... these ports are open on the public internet - even when restricted to a single IP address. I do not like to have that.

So, you don't trust the ACLs. Fair enough. You can install [port knocking](https://en.wikipedia.org/wiki/Port_knocking) to add an extra layer of security. Or you use an 127.0.0.1 ACL for the tunnel. Then you must just use the rport server as SSH jump host on the SSH client. The tunnel will not be exposed to the internet.

A feature to make rport server ports available to the clients is not planned. Sorry.

> A) Is there a way to specify more than one IP address for an open port - say 23355

If your question refers to the ACL, yes. You can enter multiple IP addresses or network ranges separated by a comma.

>  B) Is there a way that a user can only see the tunnels they created? 

No. Ports and tunnels cannot belong to a user. A TCP connection is user-less. We could internally store who has created which tunnel to hide them on the UI. But the tunnels would be discoverable anyway. 

> I want a group of users RDP all to the same server 

Why not create a single tunnel with all the IP addresses in the ACL. See above.

> and in particular not even be able to stop them

With the current permission model, this is not possible. And there are no plans to extend it. Sorry.
You can create your own small web-app on top of the API.

> On the Tunnels I cannot see whether a tunnel with be closed after some inactivity or is scheduled to be destroyed

That's correct. The UI is not displaying the information. But the API is providing it.
<img width="837" alt="image" src="https://user-images.githubusercontent.com/16852023/211260308-e752e0fa-fe13-42d1-8ad4-6eb26baf14d5.png">

**Comment by geoynomous** [comment]
Thanks a lot Thorsten for the quick replies.

I do not trust the ACL "in some way" - we're in a Co-Working space sharing the same public IP address for > 500 people (or even more). So even a single IP is exposed to more than one user. Just want(ed) to make you aware. Port Knocking and SSH are good mitigations.

In understand that port are user-less. My concern is now remote workers that connected - let's say an RDP session - and then some other user deletes the tunnel (accidentally or on-purpose). If a user added a tunnel, only that user - or an admin - should be able to delete it. Why not create a single tunnel with all IP addresses in the ACL? The IP addresses change - often. Think of like 20+ users. Plus, when a dynamic IP address is not relevant anymore, how can the tunnel be updated (i.e. removing ONE item in the comma separated list)? I think currently I need to remove the tunnel and recreate it (which stops all active connection) - or I maintain one tunnel for each IP? 

I understand that we could implement most as own app based on the API.

Would be nice to see the timeouts/auto_close in the GUI. Maybe in a property-modal (similar to "Create tunnel")
