### ISSUE TITLE
Prometheus endpoint or exporter for metrics

### ISSUE THREAD

**Issue by nwmcsween** [cloudradar-monitoring/rport#461]
This would be nice to store metrics in a timeseries database of some sort this would also allow much more broad tooling support such as alertmanager, loudml for anomaly detection, etc.

**Comment by thorstenkramm** [comment]
@nwmcsween I understand your need. My apologies for closing the request. It's extremely unlikely that we will implement a Prometheus endpoint. 
The monitoring.db has a simple structure and all measurements are stored as JSON objects. It should be straightforward to create a script that exports the data from sqlite to any format.
