### ISSUE TITLE
Connection error: websocket: bad handshake ?

### ISSUE THREAD

**Issue by Automatisator100** [cloudradar-monitoring/rport#463]
Hi
1. As described here https://kb.rport.io/install-the-rport-server/install-on-premises I have installed RPort server on Linux. 
2. Port (TCP) 8000, 20000-20050 is forwarding to RPort Server...
3. RPort server is reachable from external 

If I want to connect a Windows client (as described here https://kb.rport.io/connecting-clients) everything works. There is also no error message.

But on the RPort web interface, the client does not appear.

Test-NetConnection -ComputerName <SERVER> -Port <PORT> shows that everything is ok.

in rport.log I get the following message:
...
websocket: bad handshake
Connection error: websocket: bad handshake (Attempt: 13)
...

How can I fix this problem?

**Comment by thorstenkramm** [comment]
@Automatisator100 
Please check if a transparent proxy may block the connection. https://kb.rport.io/need-help/troubleshoot-common-problems/client-is-not-connecting
