### ISSUE TITLE
enabled RDP via browser greyed out

### ISSUE THREAD

**Issue by datazon** [cloudradar-monitoring/rport#476]
Hi,

after upgrading to 0.6, I installed debian 11 package guacamole from bitbucket and enabled guacd_address = "127.0.0.1:9445" in rportd.conf and restarted rportd service.

guacd is running on port 9445

`tcp        0      0 127.0.0.1:9445          0.0.0.0:*               LISTEN      1          641262582  128254/guacd`

The option "enabled RDP via browser" is still greyed out

Is there anything else to do?

**Comment by thorstenkramm** [comment]
@datazon 
You also need to activate the guacamole proxy in the rportd.conf in the `[server]` section.

```
  ## Host and port where guacd daemon is listening.
  ## If specified, rportd will serve remote desktop connections in browser through Apache Guacamole.
  guacd_address = "127.0.0.1:9445"
```

**Comment by HiFiPhile** [comment]
Hi,

I'm facing the same issue, in fact OP said he has already set `guacd_address = "127.0.0.1:9445"` in rportd.conf

**Comment by thorstenkramm** [comment]
@HiFiPhile 
who or what is "OP"?
Please paste the results of the following commands executed by root:
```
nc -z 127.0.0.1 9445 -v
rportd --version
netstat -tulpen|grep LISTEN
grep guacd /etc/rport/rportd.conf
cat /etc/os-release
dpkg -l|grep guacd
uname -m
```

**Comment by HiFiPhile** [comment]
> who or what is "OP"?

OP means thread opener :)


```
$ nc -z 127.0.0.1 9445 -v
localhost [127.0.0.1] 9445 (?) open

$ rportd --version
version 0.6.0


# netstat -tulpen|grep LISTEN
-- unrelated port deleted -----
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      0          14295527   173836/haproxy
tcp        0      0 127.0.0.1:9010          0.0.0.0:*               LISTEN      993        14297827   173892/rportd
tcp        0      0 0.0.0.0:9139            0.0.0.0:*               LISTEN      993        14296828   173892/rportd
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      0          14295528   173836/haproxy
tcp        0      0 127.0.0.1:9445          0.0.0.0:*               LISTEN      1          14279346   171913/guacd
tcp6       0      0 :::9000                 :::*                    LISTEN      993        14297826   173892/rportd

# grep guacd /etc/rport/rportd.conf
  ## Host and port where guacd daemon is listening.
  guacd_address = "127.0.0.1:9445"

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# dpkg -l|grep guacd
ii  rport-guacamole                       1.4.0                                            amd64        Guacamole proxy daemon (guacd) for the rport server daemon

# uname -m
x86_64
```

**Comment by HiFiPhile** [comment]
NoVNC option is also greyed out if they are related.

I followed this instruction: https://oss.rport.io/docs/no18-novnc-proxy.html#prerequisites

```
# cat /etc/rport/rportd.conf | grep novnc
  ## If specified, rportd will serve novnc javascript app from this directory.
  novnc_root = "/var/lib/rport/noVNC-1.3.0"

$ ls /var/lib/rport/noVNC-1.3.0/
app  AUTHORS  core  docs  karma.conf.js  LICENSE.txt  package.json  po  README.md  snap  tests  utils  vendor  vnc.html  vnc_lite.html
```

**Comment by thorstenkramm** [comment]
@HiFiPhile 
What's the result of `grep -B2 tunnel_proxy /etc/rport/rportd.conf`  on your system?

You need to have valid certs for the tunnel proxy too.
Guacd and NoVNC don't handle encryption. A TLS reverse proxy is needed. We call it just `tunnel_proxy`.

Example for the `rportd.conf`:
```
## Enable the creation of tunnel proxies with giving certificate- and key-file
## Defaults: not enabled
tunnel_proxy_cert_file = "/etc/letsencrypt/live/<FQDN>/fullchain.pem"
tunnel_proxy_key_file = "/etc/letsencrypt/live/<FQDN>/privkey.pem" 
```

From a browser perspective, the connection is as follows:
```
Browser -> Tunnel-Proxy -> Guacd|NoVnc
```

You can use the same cert and key for the tunnel proxy you are using for the API.

**Comment by thorstenkramm** [comment]
@HiFiPhile 
Yes. It's mandatory that the rport server handles TLS for RDP over Web and NoVNC.

The rport sever generates a reverse proxy instance on the fly on a random port to encrypt RDP and VNC over HTTPs.
Just give rportd access to the certs, and you are done. SNI is not needed in this case because rportd will not use the default API port (likely 443). It uses the port range specified in the rportd.conf in `#used_ports = ['20000-30000']`.
These ports must be directly accessible anyway. Otherwise, tunnels for SSH or any other TCP protocol won't work.

**Comment by datazon** [comment]
> ## Enable the creation of tunnel proxies with giving certificate- and key-file
> ## Defaults: not enabled
> tunnel_proxy_cert_file = "/etc/letsencrypt/live/<FQDN>/fullchain.pem"
> tunnel_proxy_key_file = "/etc/letsencrypt/live/<FQDN>/privkey.pem" 

works for me.

**Comment by HiFiPhile** [comment]
> The rport sever generates a reverse proxy instance on the fly on a random port to encrypt RDP and VNC over HTTPs.

Thanks for your explanation, now I understand better.

Since in `rport-principle.svg` there is only AES but not TLS, I thought it has a proprietary encryption protocol.
