### ISSUE TITLE
Installer fails on arm64 (Raspberry Pi Running 64 Bit Raspberry Pi OS)

### ISSUE THREAD

**Issue by Underestimated** [cloudradar-monitoring/rport#507]
Hi Team!
Have recently discovered your project and am enthused to start using the solution.
However, I've hit a snag following your tutorials.
While you state that your solution is Raspberry Pi compatible, as it currently operates, it actually isn't working 100%

![image](https://user-images.githubusercontent.com/20806875/163674316-880c806f-bdae-44e9-83d5-445f011c55dc.png)

As you can see above, when the installer calls your deployment link, it cannot find a package of rportd for the arm64 architecture.
I dug into your installer script and it looks like you have actually put a sed instruction in just before the download URL line that renames aarch64 to arm64, yet the only package your site will find is one for aarch64. Maybe your command was backwards by accident?

![image](https://user-images.githubusercontent.com/20806875/163674734-ebfae36c-9cc9-4383-9105-8a22cd3c45a9.png)

Either way I've self solved the issue by just manually typing in aarch64 at the end of the url as you can see in the screenshot but obviously you need to know about this glitch or you'll have other potential users reporting issues too.

Hopefully this helps, and thanks so much for creating a tool that is so powerful and making it Open Source!

**Comment by thorstenkramm** [comment]
@Underestimated Thank you very much for your report. Do you mind posting the issue again [here](https://github.com/cloudradar-monitoring/rportd-installer/issues)
The sever installer script has its own repository and issue tracker. I'll try to fix it asap. Seems easy.
