### ISSUE TITLE
Rportd 0.5/0.6 UI Shows ID instead of Hostname of Alpine Linux nodes.

### ISSUE THREAD

**Issue by diegomontoya** [cloudradar-monitoring/rport#510]
The Clients left menu in UI should should show hostname, not the node ID. Ubuntu nodes does not have this issue. Bug only exists for Alpine Linux nodes. 

Check attached image.

https://pasteboard.co/eOP2mpw9kz5Q.png

0.6.0 rportd also has this issue.

After going to "Inventory" tab and customizing displayed columns it appears Alpine LInux installer did not populate the "Name" attribute for Alpine linux nodes even though hostname is correctely stored as part of "Client" attribute.

**Comment by thorstenkramm** [comment]
@diegomontoya Please check the [use_hostname](https://github.com/cloudradar-monitoring/rport/blob/0.6.0/rport.example.conf#L55-L59) setting in your rport.conf. 
Even if the pairing script creates the right hostname, it's ignored unless you switch off `use_hostname`.

**Comment by diegomontoya** [comment]
@thorstenkramm You are right. `use_hostanem = false` is set on the Alpine nodes by the rport installer. Why is this config different config from the Ubuntu nodes which does not this attribute set? Fyi, we did not manually touch the /etc/rport/rport.conf before or after install.

```
## By default rport reads the local hostname to identify the system in a human-readable way.
use_hostname = false
## Optionally you can set a hard-coded name for the client.
## Useful if you use numeric ids to make client identification easier.
#name = "dnsx-uk"
```

**Comment by thorstenkramm** [comment]
It depends on if you upgraded from 0.5.x or if you did a fresh installation with 0.6.0
During an update, we don't alter existing configurations. On 0.5.x the hostname must be specified manually because using the system hostname was not supported yet. If you install 0.6.0 directly, you get the most recent default settings, which is using the systems' hostname.
