### ISSUE TITLE
Broken url (405 error):  curl -s https://pairing.rport.io/?uninstall|sudo sh

### ISSUE THREAD

**Issue by diegomontoya** [cloudradar-monitoring/rport#511]
Uninstall url in documentation doesn't work. 405 method not allowed error:

`curl -s https://pairing.rport.io/?uninstall|sudo sh`

**Comment by thorstenkramm** [comment]
@diegomontoya 
Where did you find this link? It's outdated. 
To uninstall the RPort client please execute
```
curl https://pairing.example.com/update -o rport-update.sh
sudo sh rport-update.sh -u
```

**Comment by kevs-oc** [comment]
@thorstenkramm 
It's from the kb site: https://kb.rport.io/digging-deeper/advanced-client-management/uninstall-the-rport-client

**Comment by thorstenkramm** [comment]
@shawnweeks Thanks for the reminder.
I've updated the [kb article](https://kb.rport.io/digging-deeper/advanced-client-management/uninstall-the-rport-client) now.
