### ISSUE TITLE
geodata in client install script doesn't handle quotes in name

### ISSUE THREAD

**Issue by FCoulon69** [cloudradar-monitoring/rport#514]
When geo guessed city has quotes in names, install script fails:

 sed -i s/#tags = .*/tags = ['France','Cournon-d'Auvergne']/g /etc/rport/rport.conf

+ /usr/local/bin/rport --service install --service-user rport --config /etc/rport/rport.conf
2022/04/21 11:41:09 Invalid config: error reading config file: While parsing config: (63, 29): missing comma. Check your config file.

**Comment by thorstenkramm** [comment]
Fixed with the [latest release](https://github.com/cloudradar-monitoring/rport-pairing/releases/tag/2204.21.1621) of the [Pairing Service](https://github.com/cloudradar-monitoring/rport-pairing).
