### ISSUE TITLE
rport for windows do not install or run on x86 32bits 

### ISSUE THREAD

**Issue by sandropardini** [cloudradar-monitoring/rport#515]
After download of [rport_0.6.3_Windows_x86_64.zip](url) or other versions 0.6.0 and 0.5.0 and try to install then as manual command, the error say that the application is not compatible with windows 32 bits. We do not find how to solve this issue.

**Comment by thorstenkramm** [comment]
We do not support Windows 32 bit currently, but we are open to extend our build pipeline.
But we are uncertain how big the demand for 32bit windows is. May I ask for some background information?
Which version of Windows 32bit do you use? And why do you prefer 32bit over 64bit?

**Comment by sandropardini** [comment]
Hi. thanks. We are a support service company since 1989, and we have a lot of clients with legacy applications that only run on windows 7 32 bits. How we have used the rport and all of the others operational systems 64 bits with success we have tried to install on windows 7 32 bits without success.

**Comment by thorstenkramm** [comment]
Now we have two challenges: Windows 7 (even on 64 bit a challenge) and 32 bit. 
Try to download the [0.4.0](https://github.com/cloudradar-monitoring/rport/releases/tag/0.4.0) client for Windows 32 bit.
Try to run the binary with `./rport.exe --version` just to test it's executable. If yes, try to connect to an rport server. Even this old version can connect to a recent server. 
If this works fine, Windows 7 is supported and compiling a recent version of the client on 32bit seems doable.

**Comment by thorstenkramm** [comment]
I don't see any relevant demand for 32bit Windows support. Technically, it should be possible by avoiding the usage of some modern 64bit-only libraries. But costs and benefits are not in proportion.
If some one really needs

**Comment by thorstenkramm** [comment]
I don't see any relevant demand for 32bit Windows support. Technically, it should be possible by avoiding the usage of some modern 64bit-only libraries. For now costs and benefits are not in proportion.
If someone really needs 32bit Windows clients, please ask for paid support, and we are happy to calculate the costs for you.
