### ISSUE TITLE
Intel Mac Client Install Error: sed: -I or -i may not be used with stdin

### ISSUE THREAD

**Issue by indysawmill** [cloudradar-monitoring/rport#517]
Greetings,

We are attempting to install the client on several Mac's in our office.  However, after the script is downloaded and then executed, we receive this error:

```
Success: Old config has been backed up to /etc/rport/rport.conf.bak
Success: /etc/rport/rport.conf created.
Preparing /etc/rport/rport.conf
sed: -I or -i may not be used with stdin

An error occurred.
Try running in debug mode with 'sh -x rport-installer.sh -x -i'
```

We are using the Linux Install Client, as we do not see any other options for Mac.

Thank you for your hard work on this project.

Cale

```
❯ curl -JO https://pairing.rport.io/6X1XjaJ
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file rport-installer.sh: File exists
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (23) Failed writing header
~ took 816ms 
❯ sudo sh rport-installer.sh
Password:
Installing rport client
Success: http://rmm.replaced.this:80 is reachable. All good.
Success: rport installed to /usr/local/bin/rport
rport-installer.sh: line 432: /usr/local/bin/rport: cannot execute binary file
Success: RPort  installed to /usr/local/bin/rport
Success: Old config has been backed up to /etc/rport/rport.conf.bak
Success: /etc/rport/rport.conf created.
Preparing /etc/rport/rport.conf
sed: -I or -i may not be used with stdin

An error occurred.
Try running in debug mode with 'sh -x rport-installer.sh '
Ask for help on https://github.com/cloudradar-monitoring/rport-pairing/discussions/categories/help-needed 
```

Thank you!

**Comment by Underestimated** [comment]
Check out this link, there’s a second set of documentation that covers it https://oss.rport.io/docs/no05-client-on-other-os.html#on-mac-os-intel-based

**Comment by indysawmill** [comment]
> Check out this link, there’s a second set of documentation that covers it https://oss.rport.io/docs/no05-client-on-other-os.html#on-mac-os-intel-based

Thank you for your help.  I got the executable downloaded and moved to /usr/local/bin.  However, when I attempt to execute rport, I get the following. Perhaps this is a remnant from attempting to install the Linux client?

```
❯ rport -c /etc/rport/rport.conf
2022/04/23 08:28:43 can't open log file /var/log/rport/rport.log: open /var/log/rport/rport.log: permission denied
/var/log/rport took 60ms 
❯ ls -la /var/log/rport/
total 0
drwxr-xr-x   3 root  wheel    96 Apr 23 08:23 .
drwxr-xr-x  49 root  wheel  1568 Apr 23 08:15 ..
-rw-r--r--   1 root  wheel     0 Apr 23 08:23 rport.log
```

**Comment by Underestimated** [comment]
Permissions on that file probably need to be changed, it looks like root can only write to it right now and you’re not running the client as root. Either change the file and folder owner, or adjust its permissions and I think that will solve that issue.

**Comment by indysawmill** [comment]
You were exactly right.  Some basic chmod 666 worked.  ;). Thank you again!  It appears to be working!

**Comment by Underestimated** [comment]
Fantastic! Glad I could help sort it out before the developers had to step in
