### ISSUE TITLE
Feature request: Automatic username and password pre-fill for tunnel from meta-tab

### ISSUE THREAD

**Issue by korshakov** [cloudradar-monitoring/rport#521]
It would be amazing to have as well is that if you specify username and password in your meta tab to automatically populate these fields in tunnel tab to avoid the need of copy pasting username and password. Some basic rules would have to apply such as user would must specify text key field as "username" and password as a value. To even make it more complicated (haha) key field could have value such as "rdp, username" which would mean that when RDP tunnel is to be opened the field containing rdp value would then be populated, or maybe just introduce third column in meta tab with drop down option to choose whenever or not this field is to be used for pre-fill and then choose protocol.

**Comment by thorstenkramm** [comment]
@korshakov We have already received this request several times. 

It would work only for RDP over web and for NoVNC. Injecting a password into a session or the local remote desktop app or an ssh session on a terminal is not possible. 

We are still not decided how to pass the password into the form field securely. Doing it on the frontend is an easy approach. But this might have drawbacks. We are still comparing the options.

**Comment by korshakov** [comment]
thank you
