### ISSUE TITLE
Bug: Client hostname is not updating correctly if custom hostname is specified after install

### ISSUE THREAD

**Issue by korshakov** [cloudradar-monitoring/rport#522]
I have spotted a bug where when you change hostname of a client after you install that client the hostname in the dashboard will indeed change, but when you want to add that client machine to the user group it will be showing the old hostname rather the new one this is showing in drop down area when you are about to add client machine to a group. And then it wont show in the specified group dashboard at all.

**Comment by thorstenkramm** [comment]
@korshakov What do you mean by "add that client machine to the user group"? Do you mean changing the allowed user groups of the client?
Or do you refer to client groups using the filter `Hostname is`? In deed, the hostnames on the dropdown are not updated after a client has been renamed.
<img width="1901" alt="image" src="https://user-images.githubusercontent.com/16852023/165058911-a067a7ac-5a75-4abb-a4b0-d139061bb8fe.png">

**Comment by korshakov** [comment]
Yes there as in your screenshot, apologies for misleading. Either when you are creating new client group or editing already create group.

**Comment by thorstenkramm** [comment]
Be aware of the different concepts of `Name is` and `Hostname is`.
`Hostname is` refers to the systems' hostname also known as FQDN. The rport client reads it directly from the operating system. On Unix, this is usually configured in the `/etc/hostname` file.

`Name is` refers to the client name you specified in the `rport.conf` file. By default, both are identical. But if you change the name in the `rport.conf` the system hostname remains unchanged on the operating system. 

@korshakov Does switching the filter from `Hostname is` to `Name is` solve your issue?

**Comment by korshakov** [comment]
That indeed does the trick therefore its not an issue, rather than lack of my knowledge.
