### ISSUE TITLE
Install failed on ubuntu 

### ISSUE THREAD

**Issue by kakalpa** [cloudradar-monitoring/rport#524]
My Config: 

- OS: Ubuntu 20.04.3 LTS x86_64
- Kernel: 5.4.0-109-generic
- Memory: 165MiB / 1978MiB
- CPU: Common KVM (2) @ 3.407GHz
- GPU: 00:02.0 Red Hat, Inc. Virtio GPU
- --------------------------------------------------------------------

The Issue : 

We are very sorry. Something went wrong.
Command 'touch "$DB_FILE"' exited erroneous on line 1120.

**Comment by thorstenkramm** [comment]
@kakalpa Please post the issue [here](https://github.com/cloudradar-monitoring/rportd-installer/issues). Include how did you execute the installer.
