### ISSUE TITLE
Probable websocket error

### ISSUE THREAD

**Issue by gnogeek** [cloudradar-monitoring/rport#538]
Hello,

First thanks for the development of this awesome tool,

Secondly I'm facing and issue or maybe a bug that just happens at work, 

I'm getting the following banner each time I try to add a new client I get this message:
![image](https://user-images.githubusercontent.com/77178414/167458351-9e0a80cf-63c7-4ed9-aa37-d145d7953c0a.png)

But if I try to do the same from my home network it works fine 
![image](https://user-images.githubusercontent.com/77178414/167458632-75b0e565-6f88-4b21-8290-fedb37c78974.png)

In the past I faced similar issue with Proxmox web console and solved it by configuring Nginx to enable websocket and worked perfectly.

I'm fairly noob user so probable I'm missing something.

Thanks in advance.

**Comment by thorstenkramm** [comment]
@gnogeek Can you open the dev tools of your browser while generating the pairing script fails so we can see the error message of the API?
The pairing script is generated using a public service on the internet.

**Comment by gnogeek** [comment]
> @gnogeek Can you open the dev tools of your browser while generating the pairing script fails so we can see the error message of the API? The pairing script is generated using a public service on the internet.

Hello this is what I get in the console:
![image](https://user-images.githubusercontent.com/77178414/167470395-ae4a36bb-8713-4ea7-90fb-c5b8de7e4997.png)

**Comment by thorstenkramm** [comment]
Can you try to open this test URL on the browser where it fails? `https://pairing.rport.io/eiC5pie`
Does a download start?
Try with curl or PowerShell from the command line. `iwr https://pairing.rport.io/eiC5pie`. On the PowerShell you should get Status Code:200.
If you get an error, try with different browsers and try with your mobile phone not using wifi. What happens? 
The error indicates tracking blockers, firewalls or virus scanners blocking the connection.

**Comment by gnogeek** [comment]
Thanks a lot, looks like its and issue with my work network that its blocking that address. It works perfectly outside my works.

So I will close this issue, because in fact it's and just from my side.
