### ISSUE TITLE
Windows Client installation service error

### ISSUE THREAD

**Issue by tscheiber5** [cloudradar-monitoring/rport#546]
New installations on Windows clients are unsuccessful.

Start-Service : Service 'Rport Client (rport)' cannot be started due to the following error: Cannot start service
rport on computer '.'.

Thanks for your help.

**Comment by thorstenkramm** [comment]
Fixed. https://github.com/cloudradar-monitoring/rport/releases/download/0.7.0/rport_0.7.0_Windows_x86_64.zip has been redeployed.

**Comment by tscheiber5** [comment]
@thorstenkramm thanks so much, I can confirm that it works.

**Comment by hthvdmeer** [comment]
I can confirm that it works too.
In needed to uninstall the service. Update the exe and reinstall:
C:\Users\Administrator>"C:\Program Files\rport\rport.exe" --service uninstall
Service uninstalled

C:\Users\Administrator>"C:\Program Files\rport\rport.exe" --service install  -c "C:\Program Files\rport\rport.conf"
Service installed


C:\Users\Administrator>"C:\Program Files\rport\rport.exe" --service start
Service started

That worked for me.
