### ISSUE TITLE
Question : How to give user access to client access for deploying agenmt

### ISSUE THREAD

**Issue by AC-WhiteGlint** [cloudradar-monitoring/rport#557]
Hi,

I am trying to give access to my team so that each user as access to a client access a group to deploy agent that will; on show on their assigned group.

Is there a way to achieve this.

In the UI I can see that a normal user doesn't have access to the client access tab.

Am I missing something?

**Comment by thorstenkramm** [comment]
@AC-WhiteGlint Issues are for reporting problem and bugs. To ask a question, please use the [discussion](https://github.com/cloudradar-monitoring/rport/discussions).
