### ISSUE TITLE
Improvement of 2 functions

### ISSUE THREAD

**Issue by GildedHonour** [cloudradar-monitoring/rport#56]
Here https://github.com/cloudradar-monitoring/rport/blob/master/server/api/users/parse.go#L16

and here https://github.com/cloudradar-monitoring/rport/blob/master/server/sessions/init.go#L13

a **file name string** parameter is passed as a parameter to those functions. 

While that works, it might cause an issue with creating unit tests for different types of file: empty one, normal, very big one, with different encoding, etc. 

Also, if you were to need to implement the same logic, that's in the functions, for a different data source (Http response, for instance), you'd have to duplicate a function(s), with a new data source as an argument while the body would remain the same.

To fix it,  one could replace `filename string` with `rd io.Reader` to highten the level of abstraction.

**Comment by m-terel** [comment]
@GildedHonour Please see https://github.com/cloudradar-monitoring/rport/blob/master/server/api/users/parse.go#L29 and https://github.com/cloudradar-monitoring/rport/blob/master/server/sessions/init.go#L26 . It was already done with using interfaces and covered with tests.

**Comment by GildedHonour** [comment]
Right. I'd posted an issue and then noticied that private method.
