### ISSUE TITLE
/var/lib/rport/client-auth.json file empty

### ISSUE THREAD

**Issue by guntisratkevics** [cloudradar-monitoring/rport#561]
After our rport server run out of space and we added some extra. rportd.service failed after restart with:

```
● rportd.service - Create reverse tunnels with ease.
Loaded: loaded (/etc/systemd/system/rportd.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Tue 2022-06-07 06:50:23 UTC; 5s ago
Process: 309889 ExecStart=/usr/local/bin/rportd -c /etc/rport/rportd.conf (code=exited, status=1/FAILURE)
Main PID: 309889 (code=exited, status=1/FAILURE)
CPU: 56ms

Jun 07 06:50:23 rport systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Jun 07 06:50:23 rport systemd[1]: rportd.service: Failed with result 'exit-code'.
```

which doesn't  help a lot as error message is not shown here or in /var/log/rport/rportd.log even after "debug" flag in rportd.config was added.

Found command `/usr/local/bin/rportd "-c" "/etc/rport/rportd.conf" ` in rportd.service file.
After I ran `sudo runuser -u rport -- /usr/local/bin/rportd "-c" "/etc/rport/rportd.conf"` got mesage:
`2022/06/07 07:09:41 failed to decode rport clients auth file: unexpected end of JSON input`

checked /var/lib/rport/client-auth.json and found it was empty, not sure why, but i think it could have happened when someone tried to add new client auth, but there were no space so client-auth.json could not be recreated.

**Comment by thorstenkramm** [comment]
@guntisratkevics 
If the file is empty, restore from a backup. If you have no backup, create an empty json file
```
echo '{}' > /var/lib/rport/client-auth.json
```
Once you have a valid empty file, you can use the API/UI to add client credentials.
