### ISSUE TITLE
Feature Suggestion/Request: Configurable 'Tail' files for endpoint.

### ISSUE THREAD

**Issue by Underestimated** [cloudradar-monitoring/rport#563]
Hey, Thanks again for such a useful tool! I really appreciate the effort made to deliver a solution like this.

So I had a suggestion for improvement that would be an ideal quality of life addition for me (and I'm sure others too)
On a few of my endpoints I have automated scripts run outside of the rPort infrastructure, when they run, they create a running text log file on the endpoints file system.

(For example a regular software update script writes its logs to the system, I'd like to see the status of the file regularly without remotely accessing the system interactively)

If it were possible, it would be infinitely useful to be able to define for the endpoint through the web interface a list of these log files, and when clicked, the file is 'tailed' (the last lines provided) so that we could view the current status of those logs.

I'm unsure if that's even possible right now with the current software, but as its basically just text, it may be able to be monitored and transmitted by the rport client back to the server. (much like the monitoring data currently is) and fed to the WebUI.

By doing this it makes the web interface more useful for monitoring the clients passively, as well as creates a lot of possible opportunities for enhancements down the line. 
It's a simple sort of feature, but could be a big quality of life upgrade for myself and other users who may need to monitor a lot of logs.

Thanks!

**Comment by thorstenkramm** [comment]
@Underestimated Please move this post to the [discussions](https://github.com/cloudradar-monitoring/rport/discussions). A feature request is not an issue.
😎 I've an answer prepared. Maybe you like it.
