### ISSUE TITLE
RDP via RDP client or via browser always show "null:" as destination.

### ISSUE THREAD

**Issue by PhilippRuppert** [cloudradar-monitoring/rport#564]
Hello,
I have a strange behavior after updating to version 7. The clients seem to be "online" but after creating a tunnel I can't connect to the clients anymore.
RDP via RDP client or via browser always show "null:" as destination.
I just see that this also applies to an SSH connection.
Does anyone else have this behavior ?

**Comment by thorstenkramm** [comment]
@PhilippRuppert This is a known bug that has been fixed already.
This is a pure JS/Frontend issue. Please download an updated version of the frontend
https://download.rport.io/frontend/stable/rport-frontend-stable-0.7.0-build-1026.zip
Extract the ZIP to `/var/lib/rport/docroot` overwriting all files. Refresh your browser. No need to restart rportd.

**Comment by PhilippRuppert** [comment]
Hello Thorsten,
works wonderfully.
Thank you very much!
