### ISSUE TITLE
The agent cannot re-establish connection to the server after reconnecting from the network.

### ISSUE THREAD

**Issue by ivandmitrenko** [cloudradar-monitoring/rport#570]
Hello!
When the agent service is started, an entry like this appears in the agent's log file 
`Connected (Latency XX ms)`
The agent then establishes a connection to the server and responds correctly to server commands.
However, if the physical connection to the server is interrupted, which is quite common with laptops (and somewhat less common with servers), the agent attempts to re-establish the connection. The log is appended by the entries
```
Connection error. dial tcp...
Retrying in xxx ms
```
If the physical connection is re-established at this point, the message appears.
```
Sending connection request...
Connecting...
```
But the message 
`Connected (Latency XX ms)`, as in the first case, does not appear and the server cannot send commands to the agent. The agent can only be reestablished by restarting the agent service in this case.
About 10-15 out of a hundred laptops fail in this way during the working day.
Server and agent version 0.7. Server running Debian GNU/Linux 11 (bullseye), laptops running different releases of Win10/11 
Thank you in advance

**Comment by ivandmitrenko** [comment]
Sorry, didn't read the previous bug reports. I can already see that the bug has been fixed in the current development branch.

**Comment by thorstenkramm** [comment]
@ivandmitrenko We just release 0.7.2 as pre-release. We appreciate any tests. Please download and verify your system runs stable.
