### ISSUE TITLE
Scheduled scripts editing issue

### ISSUE THREAD

**Issue by Pottty** [cloudradar-monitoring/rport#573]
If I schedule a script, then I edit that script the scheduler will still run the original version of the script.
This means, that if I want to edit a scheduled script, I have to delete the original schedule and reschedule the script after editing it.

I'm not sure if this is a bug or intended behaviour, but it is a bit annoying.

**Comment by thorstenkramm** [comment]
@Pottty Currently the behaviour is intended, but I admit it's annoying. We will change this soon so the script can be changed without deleting and re-creating it.

**Comment by thorstenkramm** [comment]
Solved with 0.8.0

<img width="1519" alt="image" src="https://user-images.githubusercontent.com/16852023/176997882-f3636136-6fb2-493a-a930-5d504a6adbbf.png">
