### ISSUE TITLE
Unsupported TLS Issues With Rport

### ISSUE THREAD

**Issue by ksakyi21** [cloudradar-monitoring/rport#574]
http: TLS handshake error from 172.168.2.13:60844: tls: client offered only u
nsupported versions: [303 302 301]

**Comment by ksakyi21** [comment]
![image](https://user-images.githubusercontent.com/39816806/173478940-100fa0e4-e523-4917-b0f1-54e5f902215b.png)

**Comment by thorstenkramm** [comment]
That's desired. Anything below TLS 1.3 is considered insecure nowadays. Which client or browser do you use? Maybe it's time for an update.

**Comment by ksakyi21** [comment]
@thorstenkramm thanks for your feedback I was able to get it to work by adding the line below to my nginx vhost location
location / {
 proxy_ssl_protocols TLSv1.2 TLSv1.3;
}
