### ISSUE TITLE
Installing rport on Windows 2012R2

### ISSUE THREAD

**Issue by srjlewis** [cloudradar-monitoring/rport#601]
Hi

Yes it is a old server, but it would be good if the installer still worked.

This is the error output I am getting

```
PS C:\Windows\system32> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS C:\Windows\system32> $url="https://pairing.rport.io/H2cfyCb"
PS C:\Windows\system32> Invoke-WebRequest -Uri $url -OutFile "rport-installer.ps1"
PS C:\Windows\system32> powershell -ExecutionPolicy Bypass -File .\rport-installer.ps1 -x -r -i
* Testing connection to http://remote.domain.com:80 has succeeded.
* RPort Client version 0.8.0 installed.
* Creating new configuration file C:\Program Files\rport\rport.conf.

#
# -------------!!   ERROR  !!-------------
#
# Installation or updare of rport finished with errors.
#

Try the following to investigate:
1) sc query rport

2) open C:\Program Files\rport\rport.log

3) READ THE DOCS on https://kb.rport.io

4) Request support on https://github.com/cloudradar-monitoring/rport-pairing/discussions/categories/help-needed


Enable-FileReception : The term 'Write-Information' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Windows\system32\rport-installer.ps1:605 char:18
+ $configContent = Enable-FileReception -ConfigContent $configContent -Switch $r
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Write-Information:String) [Enable-FileReception], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Enable-FileReception
```

**Comment by srjlewis** [comment]
@thorstenkramm 

I am now getting the following error

```
Add-Netcard : Cannot bind argument to parameter 'MessageData' because it is an empty string.
At C:\Windows\system32\rport-installer.ps1:508 char:26
+         $ConfigContent = Add-Netcard -ConfigContent $ConfigContent -Interface $n ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Netcard], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Add-Netcard
```

**Comment by thorstenkramm** [comment]
@srjlewis Sorry. My bad.
Simulate the missing `Write-Information`with the following lines:
```PowerShell
if (-not(Get-Command Write-Information -erroraction silentlycontinue))
{
    $LogFile = ".\rport-script.log"
    Write-Output "Compatibility mode for PowerShell $( $PSVersionTable.PSVersion ) activated"
    Write-Output "All information stream messages are redirected to $( $LogFile )"
    function Write-Information
    {
        Param(
            [parameter(Mandatory = $false)]
            [String] $MessageData = ""
        )
        Add-Content -Path $LogFile -Value $MessageData
    }
}
```
The input must not be mandatory. This allows writing empty strings.

**Comment by srjlewis** [comment]
@thorstenkramm 

Thanks that worked really well.

**Comment by smartekIT** [comment]
> @srjlewis Sorry. My bad. Simulate the missing `Write-Information`with the following lines:
> 
> ```powershell
> if (-not(Get-Command Write-Information -erroraction silentlycontinue))
> {
>     $LogFile = ".\rport-script.log"
>     Write-Output "Compatibility mode for PowerShell $( $PSVersionTable.PSVersion ) activated"
>     Write-Output "All information stream messages are redirected to $( $LogFile )"
>     function Write-Information
>     {
>         Param(
>             [parameter(Mandatory = $false)]
>             [String] $MessageData = ""
>         )
>         Add-Content -Path $LogFile -Value $MessageData
>     }
> }
> ```
> 
> The input must not be mandatory. This allows writing empty strings.

Hi,
Where about we should add this? which file? 
I already have the server installed on ubuntu server and I'm using the pairing server we already have installed on the same server. can't find where we put this in the files we already have on the server !
Thanks

**Comment by thorstenkramm** [comment]
@smartekIT 
The scripts are compiled into the server binary. I'll push an update to the repository, so the above changes are included. Then you must just replace the rport-pairing binary.

**Comment by smartekIT** [comment]
Thank you so much. I appreciate your help.

**Comment by thorstenkramm** [comment]
This is solved.
Next time, please open such issues [here](https://github.com/cloudradar-monitoring/rport-pairing/issues). The installer scripts have their own repository and issue tracker.
