### ISSUE TITLE
Uninstall documentation incomplete

### ISSUE THREAD

**Issue by Flachdachs** [cloudradar-monitoring/rport#602]
When uninstalling a client according to the [documentation](https://kb.rport.io/digging-deeper/advanced-client-management/uninstall-the-rport-client) only the client itself is uninstalled. It should be mentioned that additional installations also have to be uninstalled to be clean again, e.g. the TacoScript for Windows clients, preferably including how to do it.

**Comment by thorstenkramm** [comment]
@Flachdachs Thanks for the hint. The article has been [updated](https://kb.rport.io/digging-deeper/advanced-client-management/uninstall-the-rport-client).
