### ISSUE TITLE
Feature: Store any tunnel configuration

### ISSUE THREAD

**Issue by Flachdachs** [cloudradar-monitoring/rport#606]
Currently (0.8.0) only service forwardings can be stored for later use, but not tunnels to the client itself. Is there a reason why this is not possible?

**Comment by thorstenkramm** [comment]
@Flachdachs You can create a service forwarding to localhost and store it. 
But you are right. At the end, we store a tunnel config. There is no reason to require the service forwarding option. We will change this soon. Thank you for the hint.

**Comment by Flachdachs** [comment]
While you're at it, editing a temporary / not stored tunnel would be also a nice feature. As of now you can only delete the tunnel and create a new one in case you made a mistake or want to change for other reasons.

**Comment by Flachdachs** [comment]
Implemented in 0.9.x
