### ISSUE TITLE
Feature: ACL - current IP address

### ISSUE THREAD

**Issue by Flachdachs** [cloudradar-monitoring/rport#607]
When creating a tunnel configuration that can be stored (currently only service forwardings) the selection of "Only my current IP address" in "ACL, who is allowed to use the tunnel" really stores the current IP address. So far so expected, but when you (or co-workers) have a different one next time the stored configuration is useless until you change it. Additionally there is no refresh/update, you have to select one of the other options and then go back to this one.

I think this should be changed to the current IP of the one who starts the tunnel not the one who created the configuration some time ago.

**Comment by thorstenkramm** [comment]
@Flachdachs This is a valuable hint. It's queued in our backlog. But I can't promise a fast implementation. We have so many things to do.

**Comment by Flachdachs** [comment]
Implemented as "dynamic" checkbox in 0.9.x
