### ISSUE TITLE
Selecting "specific port" in tunnel configuration always proposes 3389

### ISSUE THREAD

**Issue by Flachdachs** [cloudradar-monitoring/rport#609]
When selecting "specific port" in a tunnel configuration the field is always pre-filled with 3389 (in my case at least). This should be instead a number of the configured range `used_ports`. It would also be nice that the value of `used_ports` is shown below the input field, so that you see which values are valid beforehand, not only in the error message afterwards: "Local port 3389 is not among allowed ports." This message also doesn't tell you the allowed values.

**Comment by thorstenkramm** [comment]
@Flachdachs Thanks. Good catch. That's easy to implement because all data is already loaded in the UI.
Will be implemented soon.

**Comment by Flachdachs** [comment]
implemented now in 0.9.x
