### ISSUE TITLE
Avoid geolocation during install

### ISSUE THREAD

**Issue by mgiammarco** [cloudradar-monitoring/rport#612]
I am launching the client installer in an internet limited computer (access only to *.rport.io and few other sites)
Installer stops on line 694 accessing ip-api.com for geolocation.
Can I skip this step? Can you do an installer that, in case of an error during ip-api.com step skips it?
Thanks,
Mario

**Comment by mgiammarco** [comment]
windows installer

**Comment by mgiammarco** [comment]
I can ask IT department to open ip-api.com but it seems to me not good that installer fails on a not essential steps so I told you.

**Comment by thorstenkramm** [comment]
Try with these line
```powershell
# Get the location of the server
$geoUrl = "http://ip-api.com/json/?fields=status,country,city"
try
{
    $geoData = Invoke-RestMethod -Uri $geoUrl -TimeoutSec 5
    if ("success" -eq $geoData.status)
    {
        # Add geo data as tags
        $tags += $geoData.country
        $tags += $geoData.city
    }
}
catch
{
    Write-Output ": Fetching geodata failed. Skipping"
}
```

**Comment by mgiammarco** [comment]
Yes it works I wait for inclusion in next release!

**Comment by thorstenkramm** [comment]
We published and deployed an update including the above changes. The script no longer exits if fetching geodata failed.
@mgiammarco  Thank you for reporting.

Next time, please open an issue [here](https://github.com/cloudradar-monitoring/rport-pairing/issues). 
The pairing scripts have their own repository and issue tracker.
