### ISSUE TITLE
Feature request: Ability to add hook-scripts on rport server on tunnel launch 

### ISSUE THREAD

**Issue by mdimenco** [cloudradar-monitoring/rport#622]
Add the abbility to execute hook-scripts on the rport-server when a tunnel is launched or deleted. 
Wich allows to implemtent additional notifications or configuration of an upstream reverse proxy.

**Comment by thorstenkramm** [comment]
@mdimenco 
May I ask for more details? Why do you run the tunnel ports behind a reverse proxy? Is it for security? They are protected by an ACL. In the next release, we provide additional basic auth for all HTTPS based tunnels.

**Comment by mdimenco** [comment]
Yes, primarily for security and activity monitoring. 

Alternatively a such functionality gives more flexibility in the implementation 
and gives us the ability to implement a proxy prior the rport appliance for protocols or application wich wich not allows to change the TCP-port and we can route dirrerent domain names or ip adresses  on the smae port to the rport server to the edicaten TCP Ports. 
                                                    ------------
--->   alias1.domain.net:445 -->|                  |  ----> rport.domain.net:20001
          alias2.domain.net:445 -->|  proxy       |  ----> rport.domain.net:20003
          alias3.domian.net:80   -->|                  |  ----> rport.domian.net:20004
                                                    ------------
                                                            ^
                                                             '--------------- configuration witch hoock scripts on tunnel launch or deletion (shell script)

**Comment by thorstenkramm** [comment]
@mdimenco I understand your approach. 
Our goal is to make rport secure without the need of external measures such as reverse proxies or dynamically created port forwarding or firewall rules. 
I'm sorry, but we won't implement such hooks in the near future.
But look here https://serverfault.com/questions/717651/notify-when-a-tcp-port-start-listening
Maybe you can implement the hook with auditd and `auditctl`.
