### ISSUE TITLE
Issues with RPort behind Reverse Proxy 

### ISSUE THREAD

**Issue by vveerar1** [cloudradar-monitoring/rport#642]
Hi, I followed Awesome Open Source's [video](https://www.youtube.com/watch?v=Xc_5qE7ZyYA) to set up an LXC container for RPort. I am trying to place RPort behind reverse proxy. I copied the certificates from my reverse proxy and changed the path in `rportd.conf` file.  The application works with the new certificate locally on `https://localhost:5000/` but not accessible outside on `https://rport.subdomain.com`. Am I missing something? 

PS: I am using reverse proxy using SWAG docker container with a Cloudflare tunnel.

**Comment by thorstenkramm** [comment]
RPort is static single binary software. It contains everything it needs. If you really get a great benefit from running RPort inside an LXC container depends on your setup. Users often achieve the opposite.
 
If it works locally but not from the internet, your reverse proxy seems to be the problem.
RPort only talks TLS 1.3. Some proxies like Nginx need to be forced to use TLS 1.3. They still use TLS 1.2 by default.
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/ 
```
location /upstream {
        #...
        proxy_ssl_protocols TLSv1.3;
        proxy_ssl_ciphers   HIGH:!aNULL:!MD5;
}
``` 

**Next time, please ask your question on the [discussions](https://github.com/cloudradar-monitoring/rport/discussions).** 
Your question is not an issue in the sense of a RPort failure.
