### ISSUE TITLE
Guacamole Server not Utilized

### ISSUE THREAD

**Issue by sempervictus** [cloudradar-monitoring/rport#679]
We use Arch Linux at Semper Victus, and have set up builds/packaging for the Go  and web UI pieces of `rport` accordingly. During the process, i took a look at how the Debian packges for guacd were set up and did not see any custom patching or anything of that nature - seems a pretty straightforward source build from upstream. Since we already have guacamole building for our OpenUDS environment, it seems rational to reuse that component here.

So, we have our `guacd` running on the Rport server:
```shell
# systemctl status guacd
● guacd.service - Guacamole Server
     Loaded: loaded (/usr/lib/systemd/system/guacd.service; enabled; preset: disabled)
     Active: active (running) since Sun 2022-08-28 02:12:59 UTC; 11h ago
       Docs: man:guacd(8)
   Main PID: 5651 (guacd)
      Tasks: 1 (limit: 4654)
     Memory: 10.0M
        CPU: 19ms
     CGroup: /system.slice/guacd.service
             └─5651 /usr/bin/guacd -f

Aug 28 02:12:59 sv-rp00 systemd[1]: Started Guacamole Server.
Aug 28 02:12:59 sv-rp00 guacd[5651]: Guacamole proxy daemon (guacd) version 1.4.0 started
Aug 28 02:12:59 sv-rp00 guacd[5651]: guacd[5651]: INFO:        Guacamole proxy daemon (guacd) version 1.4.0 started
Aug 28 02:12:59 sv-rp00 guacd[5651]: guacd[5651]: INFO:        Listening on host 127.0.0.1, port 4822
Aug 28 02:12:59 sv-rp00 guacd[5651]: Listening on host 127.0.0.1, port 4822
```
and configured in `rportd.conf` as `guacd_address = "127.0.0.1:4822"` but the in-browser remote desktop option is grayed-out (cannot be checked):
![image](https://user-images.githubusercontent.com/1331084/187077518-5f11c390-58ac-4d0f-8fe8-7988bf96d0b1.png)

Am i missing a configuration option or do i need to somehow patch and rebuild a custom `guacd` for Rport?

**Comment by thorstenkramm** [comment]
@sempervictus Could you solve it?
Please re-open if not.
