### ISSUE TITLE
Fedora Silverblue: SELinux

### ISSUE THREAD

**Issue by djarbz** [cloudradar-monitoring/rport#685]
The current documentation page for SELinux is blank.
I would like to add my Fedora Silverblue PC as a client.

https://kb.rport.io/digging-deeper/advanced-client-management/run-with-selinux

**Comment by thorstenkramm** [comment]
@djarbz Maybe [this link](https://github.com/cloudradar-monitoring/rport-pairing/discussions/3#discussioncomment-2998671) helps you to create the SELinux policies.

**Comment by djarbz** [comment]
Yes, that worked!
