### ISSUE TITLE
Installation script, didnt work because DNS check fails

### ISSUE THREAD

**Issue by GitHub-Lover** [cloudradar-monitoring/rport#696]
Installation script from https://get.rport.io (downloaded today) refers to https://cloudflare-dns.com/dns-query.

This url https://cloudflare-dns.com/dns-query does not exist (anymore), so the script can not check if the DNS-Name is set on a domain or not.

**Comment by thorstenkramm** [comment]
@GitHub-Lover Thank you very much for reporting.
The URL has been replaced by `https://1.1.1.1/dns-query` which is the correct way how Cloudflare wants DNS queries to be executed over https.
