### ISSUE TITLE
Docker info check logs

### ISSUE THREAD

**Issue by kendinitekmeleyenkedi** [cloudradar-monitoring/rport#709]
Hi Everyone,

On servers with docker and kubernetes installed, login logs are constantly created as in the picture. Although the monitoring feature is turned off in rportd and rport configurations and the agents are restarted, these logs do not stop. This situation is perceived as false positive by Siem.

How can we stop this situation and why is it constantly monitoring?

![image](https://user-images.githubusercontent.com/69451768/193243895-d889586a-c240-44f1-a978-77bcb425768d.png)

Thx.

**Comment by kendinitekmeleyenkedi** [comment]
Hİ,

The situation I'm talking about is still going on, does anyone have an idea?

**Comment by thorstenkramm** [comment]
@kendinitekmeleyenkedi Which version are you running on the client?
The docker issue has been resolved with [0.8.6](https://github.com/cloudradar-monitoring/rport/releases/tag/0.8.6).

**Comment by kendinitekmeleyenkedi** [comment]
Hİ @thorstenkramm,

First of all thanks for the reply. Version information is as follows, I'll check for updates and will feedback.

Server API Version: 0.8.0
Frontend Version: rport-frontend-stable-0.8.0-build-1092
Client Version: 0.8.0

Thx.

**Comment by kendinitekmeleyenkedi** [comment]
Hi @thorstenkramm,

I updated the rport server and one client to 0.8.7 versions, the problem seems to be solved. Thanks.
