### ISSUE TITLE
connection_state filter either misdocumented or is bugged

### ISSUE THREAD

**Issue by AzraelArchitect** [cloudradar-monitoring/rport#711]
I'm using rport version 0.8.0

The documentation at https://apidoc.rport.io/master/#tag/Clients-and-Tunnels/operation/ClientsGet has `connection_state` listed as a valid filter for the API. Trying to filter  using `api/v1/clients?filter[connection_state]=connected` returns the following

```
{
  "errors": [
    {
      "code": "",
      "title": "unsupported filter field 'filter[connection_state]'",
      "detail": ""
    }
  ]
}
```

Is anyone else able to reproduce this issue or is something broken on my end?

**Comment by AzraelArchitect** [comment]
Does anyone have any info on this? It's been 18 days without a peep from anyone.

**Comment by thorstenkramm** [comment]
@AzraelArchitect You are looking at the API docs of the current master branch. This does not reflect the state of 0.8.0. The filter you are seeking has been introduced after 0.8.0, so you have to wait for 0.9.0. (Will be released before end of October 2022)
With the next release, we also introduce versioned API docs to avoid such a confusion.
