### ISSUE TITLE
Feature Request: Add ability to rename or create Alias and add custom tags via the Dashboard

### ISSUE THREAD

**Issue by sagararyal** [cloudradar-monitoring/rport#720]
After having deployed rport to around 20 machines, something I think would help with management is an easier interface to edit names, or create alias, and add tags from the dashboard.

![Screen Shot 2022-10-11 at 11 02 42 PM](https://user-images.githubusercontent.com/5401575/195198445-fa22d59b-ee6c-4f09-a341-bd0238483028.png)

Alias can also be stored on the server only, if desired.

This can be further extended to allow search by Tags.
![Screen Shot 2022-10-11 at 11 08 55 PM](https://user-images.githubusercontent.com/5401575/195198738-1563e639-7b30-4880-94fb-88a14d496528.png)

I understand that these are cosmetic changes, which are possible by modifying the rport.conf file, however to make it easy to edit it, I think a simple script can run a find and replace and restart rport, eg. below:

```
$filePath = 'C:\Program Files\rport\rport.conf'
$tempFilePath = "$env:TEMP\$($filePath | Split-Path -Leaf)"
$find = '#name = "my_win_vm_1"'
$replace = 'name = "NEW-NAME-XX"'

(Get-Content -Path $filePath) -replace $find, $replace | Add-Content -Path $tempFilePath

Remove-Item -Path $filePath
Move-Item -Path $tempFilePath -Destination $filePath
```

**Comment by sagararyal** [comment]
Duplicate #588

**Comment by bloesss** [comment]
If you run this script, the resulting conf-file would be readable only to the system account
