### ISSUE TITLE
QUESTION: is project not continue after realVNC acquires RPort ?

### ISSUE THREAD

**Issue by albasyir** [cloudradar-monitoring/rport#746]
From RealVNC website and rport.io site, we know that : 

<img width="843" alt="image" src="https://user-images.githubusercontent.com/28939309/197587785-3a32be47-0dcd-4b3f-85fb-63c22c5e0c4e.png">

RealVNC Article : 
https://www.realvnc.com/en/news/realvnc-acquires-rport-remote-management-software/

QUESTION : 
shall we carry out this opensource project or will this project be updated?

**Comment by thorstenkramm** [comment]
RPort will continue, and it will continue as an open-source project. The engagement of RealVNC is a unique opportunity to boost the development. RealVNC will invest budget and resources. The owner change will not have a negative impact. 
Quite the opposite. **The product and all open-source users will benefit from the stable financing.** 

@albasyir Do not abuse the issue tracker for such messages again. Next time, use the [discussions](https://github.com/cloudradar-monitoring/rport/discussions).
