### ISSUE TITLE
Enabling Basic auth does nothing 

### ISSUE THREAD

**Issue by bloesss** [cloudradar-monitoring/rport#765]
I just Tried to enable Basic auth in Reverse Proxy Tunnels in 0.9.0.

all Tunnels became incredible Slow, but There was no Need to enter credantials anywhere. After 5 Minutes, all Tunnels stopped working and I Could Not Use any Commands or scripts anymore. I Had to Reboot the rportd server, restarting rportd didnt help. But cpu usage was 0%

**Comment by thorstenkramm** [comment]
What kind of web-based app did you use over the tunnel? Does this app use web sockets?

**Comment by thorstenkramm** [comment]
@bloesss 
> but There was no Need to enter credantials anywhere

If you clicked on the "Launch Tunnel" icon, the username, and password were appended to the open link. That's why your are not prompted. Try to open the tunnel on a different browser. You will be asked for credentials.

**Comment by bloesss** [comment]
OK thank you, didn't know that there has to be no question for the credentials.
I will try to reproduce it
