### ISSUE TITLE
Minor bug - Scripts Library - Cannot modify the Time out

### ISSUE THREAD

**Issue by MarcSamD** [cloudradar-monitoring/rport#802]
The default time out is 60 seconds.
If I edit a script, I can modify the fields (like scriptname, interpreter or timeout) and save.
The fields are correctely updated except the timeout that is always revert to 60 seconds.
![image](https://user-images.githubusercontent.com/70358310/203210284-6eefc22d-42af-4914-bece-466d44e2d7fd.png)

**Comment by thorstenkramm** [comment]
@MarcSamD Which version of RPort and RPort frontend are you using? (Click `more` -> `info`)
I can't reproduce with the latest version.

**Comment by MarcSamD** [comment]
I was using 0.8.0, I don't have this issue anymore after upgrading to 0.9.0.

Meanwhile, there is a very nice orange banner when "The client runs an old version of Rport.". I didn't see such notification for the server part, which would be good to have (if not already done in 0.9.0 :)

And last but not least, congrats for the work, this is a promising project.
