### ISSUE TITLE
Docs Improvement: Change the FQDN of the RPort server

### ISSUE THREAD

**Issue by etec-masterofsynapse** [cloudradar-monitoring/rport#835]
I would like to propose three additional paragraphs for the docs page https://kb.rport.io/install-the-rport-server/change-the-fqdn-of-the-rport-server :

- **Change the tunnel_host url**
If rport is behind a reverse proxy like Cloudflare Tunnel&Access and the WebUI runs on a different FQDN, this field will be filled and the same as the client connect url. So it should be mentioned that in this case the value of tunnel_host must be changed too.
- **Change totp_account_name**
When using TOTP as the second login factor, this field is filled. If the admin chose the FQDN of the server as the value for this field, this value should be changed in line with the FQDN change of the server.
- **Cleanup old cert(s) via certbot**
After rportd is running again and uses the new cert for the new FQDN, the old cert should be removed or else certbot would try to renew this one regularly too, at worst running into DNS resolution errors since the old FQDN doesn't exist anymore.
A clean cleanup (haha ;) ), can be achieved by running `certbot delete` and selecting the old cert via the corresponding number key.

**Comment by thorstenkramm** [comment]
@etec-masterofsynapse 🙌 Brilliant. Thank you so much.
I've updated the page with all your suggestions. 
😀
