### ISSUE TITLE
Feedback link in 0.9.0 not working

### ISSUE THREAD

**Issue by Evo-c** [cloudradar-monitoring/rport#849]
**Describe the bug**
The feedback link found under settings does not work in 0.9.0 - It currently links to https://feedback.rport.io/feedback.html which does not exist.

In case you know it. Is the bug related to `rportd` (server) or `rport` (client)?
**`rportd`**

**Environment**
Describe the environment where the bug occurs: **Web interface settings**
* RPort version **0.9.0**
* OS details (Linux distribution, and version or Windows version) **N/A**
* Is rportd running inside a docker container? **N/A**
* Are you using a reverse proxy? If yes, which one? **N/A**

**Screenshots**
[https://lolcatho.st/cat/me0wb6q.jpg](https://lolcatho.st/cat/me0wb6q.jpg)

**Comment by thorstenkramm** [comment]
@Evo-c Thanks for reporting.
This will be fixed with the next release. I close this issue right now because it's duplicated.
