### ISSUE TITLE
Update of rportd 0.8 -> 0.9.5 failed

### ISSUE THREAD

**Issue by mtelahun** [cloudradar-monitoring/rport#859]
I tried updating rportd from 0.8 to 0.9.5 using the instructions provided in the update instructions:
```
curl -s https://get.rport.io/update -o rportd-update.sh
bash rportd-update.sh
```

This is the output from the script. Should I have updated to each release individually instead of trying to jump from 0.8 to 0.9.5 directly?

[*] A backup has been created in /var/backups/rportd-20221223-135938.tar.gz
[*] /usr/local/bin/rportd updated to version 0.9.5
[*] Performing database migrations where needed.
[*] Reverse Proxy already activated
[*] Monitoring is already enabled.
[*] Plus plugin inserted but NOT activated. https://kb.rport.io/digging-deeper/rport-plus
[*] Migrated config 'keep_lost_clients' to 'keep_disconnected_clients'.
[*] /usr/local/bin/2fa-sender.sh backed to /tmp/2fa-sender.sh
[*] /usr/local/bin/2fa-sender.sh updated
Error: near line 3: in prepare, table "group_details" already exists (1)

**Comment by thorstenkramm** [comment]
@mtelahun Thank you for reporting this issue.
There was a duplicated SQL statement in the script. We fixed it. Try the update again.

**Comment by mtelahun** [comment]
Thank you. It works now.
