### ISSUE TITLE
Wrong DB file name in documentation

### ISSUE THREAD

**Issue by rdeago** [cloudradar-monitoring/rport#861]
**Describe the bug**

The "Use push on mobile for 2FA" page in RPort's knowledge base contains instructions on using Pushover for 2FA notifications.

Unfortunately, the instructions given to update RPort's database contain the wrong DB file name (as of version 0.9.0).

This is the relevant section of the page: https://kb.rport.io/install-the-rport-server/enable-two-factor-authentication/use-push-on-mobile-for-2fa#update-the-database

The first line of shell code reads:

```sh
DB_FILE=/var/lib/rport/user-auth.db
```

It should instead read:

```sh
DB_FILE=/var/lib/rport/auth.db
```

**Comment by thorstenkramm** [comment]
@rdeago Thanks for the hint. I've changed the documentation.
