### ISSUE TITLE
RPort server not starting after update 0.9.0 -> 0.9.5

### ISSUE THREAD

**Issue by rdeago** [cloudradar-monitoring/rport#862]
**Describe the bug**

I just updated my RPort server from version 0.9.0 to 0.9.5 by following [these instructions](https://kb.rport.io/digging-deeper/server-maintenance/updating-rport#update-the-rport-server) and now the `rportd` service fails upon starting.

```shell
root@myserver:~# systemctl status rportd
● rportd.service - Create reverse tunnels with ease.
     Loaded: loaded (/etc/systemd/system/rportd.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-12-27 15:54:42 CET; 1min 35s ago
    Process: 1393 ExecStart=/usr/local/bin/rportd -c /etc/rport/rportd.conf (code=exited, status=1/FAILURE)
   Main PID: 1393 (code=exited, status=1/FAILURE)
        CPU: 151ms

Dec 27 15:54:42 myserver.mydomain.net systemd[1]: rportd.service: Main process exited, code=exited, status=1/FAILURE
Dec 27 15:54:42 myserver.mydomain.net systemd[1]: rportd.service: Failed with result 'exit-code'.
```

This is what is written to `/var/log/rport/rportd.log`, even with `log_level = "debug"` in `/etc/rport/rportd.conf`:

```text
2022/12/27 15:54:42 info: rport-plus: not enabled
2022/12/27 15:54:42 info: server: Fingerprint <REDACTED>
2022/12/27 15:54:42 info: server: data directory path: "/var/lib/rport"
2022/12/27 15:54:42 info: server: initialized database at /var/lib/rport/monitoring.db
2022/12/27 15:54:42 info: server: DB: successfully connected to /var/lib/rport/auth.db
```

Restarting the `rportd` service (`systemctl start rportd`) takes a long time (up to 2 minutes) and gives no messages, but then the status is as shown above (and there are 5 more lines in the log, identical to the above except for the timestamps).

**EDIT:** I just noticed that the same 5 lines are appended to the log every two minutes. `systemctl status rportd` still says the service failed, though, and `ps` reports no `rportd` process. Could it be `systemd` retrying to start the service?

**Environment**

* RPort version 0.9.5
* Debian Linux 5.10.158-2 (2022-12-13) x86_64, kernel 5.10.0-20-amd64 (in other words, Debian 11 with all latest updates)
* No Docker, just plain Debian and a couple utility programs (mc, tilde)
* No reverse proxy, if you don't count the one provided by RPort itself
* 2FA notifications via Pushover (tested and working with 0.9.0)

**Comment by rdeago** [comment]
Looks like the `auth` database was not migrated correctly.

I found the following message in the systemd journal:

```
no such column: password_expired, if you have 2fa enabled please check additional column requirements at https://oss.rport.io/docs/no02-api-auth.html#database
```

The following bash command solved the problem:

```
sudo sqlite3 /var/lib/rport/auth.db <<< 'ALTER TABLE users ADD COLUMN "password_expired" bool NOT NULL default false;'
```

Did I fail to do something after updating the RPort server? As far as I can remember, the update script ran smoothly and issued no error or warning messages.

**Comment by Anganthier** [comment]
I had the same problem and found the solution in the release notes to 0.9.1:
![image](https://user-images.githubusercontent.com/15246122/209787558-5982d6ac-4bef-41c0-942e-3aed4edfa83b.png)

It is almost the exact sql statement you are using.

**Comment by t347s** [comment]
Hi,
Same issue here, thank you all for reporting, the solution was the following bash command: 
`
sudo sqlite3 /var/lib/rport/auth.db <<< 'ALTER TABLE users ADD COLUMN "password_expired" BOOLEAN NOT NULL CHECK (password_expired IN (0, 1)) DEFAULT 0;'
`

Best regards

**Comment by rdeago** [comment]
> I had the same problem and found the solution in the release notes to 0.9.1:

I didn't even know there was a version 0.9.1. 🙈 I received the newsletter about the 0.9.5 release and followed the instructions.

> It is almost the exact sql statement you are using.

As @Anganthier pointed out, the statement I used was intended for MySQL: SQLite happily accepted it, but it lacks the "boolean values only" check. I found the statement by doing a GitHub search of "password_expired" in this repo. I probably should not have stopped at the first result vaguely resembling a CREATE TABLE statement. 😁 Even more probably, I should have taken a look at the release notes. Silly me.

**Comment by rdeago** [comment]
Just in case someone made my same mistake, here's how I fixed the `users` table on my server (Debian 11, SQLite 3.34.1):

```bash
sudo systemctl stop rportd
sudo sqlite3 /var/lib/rport/auth.db <<EOT
CREATE TABLE "users2" (
  "username" TEXT(150) NOT NULL,
  "password" TEXT(255) NOT NULL,
  "password_expired" BOOLEAN NOT NULL CHECK (password_expired IN (0, 1)) DEFAULT 0,
  "token" TEXT(36) DEFAULT NULL,
  "two_fa_send_to" TEXT(150),
  "totp_secret" TEXT DEFAULT ""
);
DROP INDEX "main"."username";
CREATE UNIQUE INDEX "main"."username" ON "users2" (
  "username" ASC
);
INSERT INTO "users2" SELECT
  "username",
  "password",
  "password_expired",
  "token",
  "two_fa_send_to",
  "totp_secret"
FROM "users";
DROP TABLE "users";
ALTER TABLE "users2" RENAME TO "users";
EOT
sudo systemctl stop rportd
```
