### ISSUE TITLE
Feature: Prompt for permission

### ISSUE THREAD

**Issue by wzrdtales** [cloudradar-monitoring/rport#865]
A nice feature would be for desktop machines, that you could deactivate remote access by default and let the user decide to allow the admin intervention. This way this could be used also on desktop machines, by making a prompt to be clicked yes first, for certain commands to be executed.

**Comment by thorstenkramm** [comment]
@wzrdtales Thanks for your suggestion. 
Please respect our policies. The issue template states, clearly, that feature requests are collected on the discussion forum. A feature request is not an issue.
Also, your request has many similarities with other requests. We are working on a professional desktop user support solution.
