### ISSUE TITLE
Port 3389 is not in listening state.

### ISSUE THREAD

**Issue by zioneum** [cloudradar-monitoring/rport#874]
Hi,

I'm having some trouble getting to RDP to a client , i'm not behind a firewall or anything just trying to see how the RDP works

Cheers

**Comment by thorstenkramm** [comment]
@zioneum We had similar reports.

Did you activate RDP on the remote machine? It's disabled by default.

If RDP is enabled, and you are still getting the error, it is very likely caused by an antivirus or other security software. Switch them all off and test again.

**Comment by zioneum** [comment]
You Were correct thank you very much , but the thing is i was looking to get connected the same way PulseWay or VSA Does it without kicking out the current user , VNC Says Port 5900 is not in listening state

**Comment by zioneum** [comment]
Thank you i'll give it a try
