### ISSUE TITLE
Does affect current clients created by Client Access the refreshing of API token?

### ISSUE THREAD

**Issue by cryptodev4** [cloudradar-monitoring/rport#881]
**Question about API token**

This question is because when I try to refresh API token it says something like:

" A previously generated token will be overwritten. Clients and scripts might stop working. Do you want to continue?"

I would like to know because I don't remember the last API token generated.

**Environment**

Using Rport on production environment for IoT devices.

* RPort version: 0.9.5
* OS details (Linux distribution, and version or Windows version): Debian 11 Bulleye
* Is rportd running inside a docker container? No
* Are you using a reverse proxy? If yes, which one? We currently use Cloudflare but Rport Server is not proxied.

**Comment by thorstenkramm** [comment]
@cryptodev4 
Please do not create issues for asking questions. We have a [discussion forum](https://github.com/cloudradar-monitoring/rport/discussions) for that.

The answer to your question is no. API tokens and their renewal does not affect connected clients. Clients use their own separated authentication.
