### ISSUE TITLE
rport 0.9.5 crashes frequently `Client configuration does not allow tunneling destination`

### ISSUE THREAD

**Issue by BinhPhuongIT** [cloudradar-monitoring/rport#882]
rport 0.9.5 crashes frequently `Client configuration does not allow tunneling destination`
i had to restart the rport client for it to work. But got 1 time and then got another.
This error occurs on all clients.

**Comment by thorstenkramm** [comment]
@BinhPhuongIT 
Please do not ignore the template for issue creation. We are happy to help you, but we need additional information. The most important info is the operating system? Please add the full version of your client OS.
Doe the client or the server crash?
If the server crashes, which OS is it running on?
Do you have [tunnel rules](https://github.com/cloudradar-monitoring/rport/blob/0.9.5/rport.example.conf#L88-L103) in your client configuration?

**Comment by BinhPhuongIT** [comment]
Hi team,

Rport Server version 0.9.5 running on Ubuntu 22.04
Rport Client version 0.9.5 runs on Windows 10 and Windows 11.

The server is still working normally.

For example, I have 10 clients (Windows 10, 11), there will be some clients reporting the above error (I fixed it by run powershell ''Service-Restart rport'') .

but this is a temporary solution, because the problem persists.

Note: all tunneling services fail (VNC, SSH, RDP, ...)

Thanks!

**Comment by BinhPhuongIT** [comment]
> @BinhPhuongIT Please do not ignore the template for issue creation. We are happy to help you, but we need additional information. The most important info is the operating system? Please add the full version of your client OS. Doe the client or the server crash? If the server crashes, which OS is it running on? Do you have [tunnel rules](https://github.com/cloudradar-monitoring/rport/blob/0.9.5/rport.example.conf#L88-L103) in your client configuration?

**Comment by thorstenkramm** [comment]
@BinhPhuongIT Do you have a virus scanner running? Turn off just to test if this helps. Many other users have reported that some virus scanners kill the rport process when a tunnel should be created.

**Comment by BinhPhuongIT** [comment]
I turned off virus scanner but still the same. I don't think the Rport process is killed. because I can still execute Scripts from Rport Server.
![image](https://user-images.githubusercontent.com/69758987/212282773-34d14360-964c-481d-9ae8-af3675ac9ce3.png)
![image](https://user-images.githubusercontent.com/69758987/212282995-ad8f6578-38a3-4c6d-8b1d-48809b705b47.png)

The services I call directly to the client are still working normally.

**Comment by thorstenkramm** [comment]
Do you have [tunnel rules](https://github.com/cloudradar-monitoring/rport/blob/0.9.5/rport.example.conf#L88-L103) in your client configuration?

Is the VNC server up and running? (You need to install some. The client does not have a VNC server built-in.)

**Comment by BinhPhuongIT** [comment]
Make sure VNC server is working, as I mentioned above that after restarting rport client the tunnel works.

This is client configuration for  tunnel rules.

## By default the rport client can create tunnels to any network address.
  ## This way the so-called "service forwarding" can give access to entire networks.
  ## You can turn service forwarding off so tunnels must end on the local machine.
  #tunnel_allowed = ['127.0.0.0/8']
  ## Alternatively to the above, you can explicitly allow which targets a tunnel is allowed to reach.
  ## By default, no limits are applied
  ## List items can be a single IP or CIDR specification allowing to reach all ports on the target
  ## or an IP address or a CIDR specification and a port separated by a colon.
  ## Using ':<PORT>' without IP address or CIDR is a shorthand for '127.0.0.0/8:<PORT>'
  ## Examples:
  ## Only RDP on localhost can be accessed
  #tunnel_allowed = ['127.0.0.0/8:3389']
  ## Only SSH on localhost and SSH on 192.168.1.1 can be accessed.
  #tunnel_allowed = [':22','192.168.1.1:22']
  ## Only HTTP on localhost, and RDP to any host on the 192.168.1.0/24 network, and all ports on 192.168.1.100 can be accessed.
  #tunnel_allowed = [':80','192.168.1.0/24:3389','192.168.1.100']

**Comment by thorstenkramm** [comment]
@BinhPhuongIT  Hm. No rules active. 
Please [activate the debug log](https://github.com/cloudradar-monitoring/rport/blob/0.9.5/rport.example.conf#L169-L171), restart the client and observe the log file and the windows' event log. Maybe some hints are logged there.
