### ISSUE TITLE
Client disconnects randomly and never connects back until manual service restart

### ISSUE THREAD

**Issue by Shivangraj** [cloudradar-monitoring/rport#905]
**Describe the bug**
Hey facing this issue for a while now, Client gets disconnected randomly and never connects back online until I restart services manually. 

the bug related to `report` (client)

**Environment**
Describe the environment where the bug occurs:
* RPort version
9.5
* OS details (Linux distribution, and version or Windows version)
Gentoo
* Is rportd running inside a docker container?
No
* Are you using a reverse proxy? If yes, which one?
NO

**Log file**
2023/02/07 01:22:33 error: client: Failed to send keepalive (client to server ping): conn.SendRequest(ping), timeout 30s exceeded
2023/02/07 01:22:33 error: client: Monitoring ended by context.Done
2023/02/07 01:22:33 info: client: Disconnected
2023/02/07 01:22:33 info: client: Trying to connect to ws://rxxxxxxxxxxx:80 ...
2023/02/07 01:22:33 info: client: Server's full fingerprint xx:xx:xx:xx:fc:xx:xx:xx:42:c1:xx:xx:f5:ad:64:xx
2023/02/07 01:22:33 info: client: Sending connection request.
2023/02/07 01:22:33 error: client: Connection error: Local port 22876 already in use.
2023/02/07 01:22:33 info: client: Retrying in 100ms...
2023/02/07 01:22:34 info: client: Trying to connect to ws://rxxxxxxxxxxx:80 ...
2023/02/07 01:22:34 info: client: Server's full fingerprint xx:xx:xx:xx:fc:xx:xx:xx:42:c1:xx:xx:f5:ad:64:xx
2023/02/07 01:22:35 info: client: Sending connection request.
2023/02/07 01:22:35 info: client: Connected to xx.xxx.xxx.xxx:80 within 155.240014ms
2023/02/07 01:22:50 info: client: Disconnected
2023/02/07 01:22:50 error: client: Connection error: read tcp 10.xx.xxx.101:44580->xx.xxx.xxx.xxx:80: read: connection reset by peer
2023/02/07 01:22:50 info: client: Retrying in 100ms...
2023/02/07 01:22:50 error: client: Monitoring ended by context.Done
2023/02/07 01:22:50 info: client: Trying to connect to ws://rxxxxxxxxxxx:80 ...
2023/02/07 01:22:51 info: client: Server's full fingerprint xx:xx:xx:xx:fc:xx:xx:xx:42:c1:xx:xx:f5:ad:64:xx
2023/02/07 01:22:51 info: client: Sending connection request.
2023/02/07 01:22:51 info: client: Connected to xx.xxx.xxx.xxx:80 within 79.02933ms
2023/02/07 01:23:36 info: client: Disconnected
2023/02/07 01:23:36 error: client: Connection error: read tcp 10.xx.xxx.101:41026->xx.xxx.xxx.xxx:80: read: connection reset by peer
2023/02/07 01:23:36 info: client: Retrying in 100ms...
2023/02/07 01:23:36 info: client: Trying to connect to ws://rxxxxxxxxxxx:80 ...
2023/02/07 01:23:37 info: client: Server's full fingerprint xx:xx:xx:xx:fc:xx:xx:xx:42:c1:xx:xx:f5:ad:64:xx
2023/02/07 01:23:37 info: client: Sending connection request.
2023/02/07 01:23:37 info: client: Connected to xx.xxx.xxx.xxx:80 within 70.464884ms
2023/02/07 02:08:38 info: client: Disconnected
2023/02/07 02:08:38 error: client: Connection error: read tcp 10.xx.xxx.101:45860->xx.xxx.xxx.xxx:80: read: connection reset by peer
2023/02/07 02:08:38 info: client: Retrying in 100ms...
2023/02/07 02:08:38 error: client: Monitoring ended by context.Done
2023/02/07 02:08:38 info: client: Trying to connect to ws://rxxxxxxxxxxx:80 ...
2023/02/07 02:08:38 info: client: Server's full fingerprint xx:xx:xx:xx:fc:xx:xx:xx:42:c1:xx:xx:f5:ad:64:xx
2023/02/07 02:08:38 info: client: Sending connection request.
2023/02/07 02:08:39 info: client: Connected to xx.xxx.xxx.xxx:80 within 74.357741ms
2023/02/07 02:10:35 info: client: Disconnected
2023/02/07 02:10:35 error: client: Connection error: read tcp 10.xx.xxx.101:34008->xx.xxx.xxx.xxx:80: read: connection reset by peer
2023/02/07 02:10:35 info: client: Retrying in 100ms...
2023/02/07 02:10:35 error: client: Monitoring ended by context.Done
2023/02/07 02:10:35 error: client: Failed to send keepalive (client to server ping): EOF

**rport.conf file**
```
[connection]
  ## An optional keepalive interval. The client will send ping request at this interval.
  ## You must specify a time with a unit, for example '30s' or '2m'.
  ## Defaults to '3m', '0s' = disabled
  #keep_alive = '3m'

  ## Timout for the above keep_alive after which the connections is considered disconnected.
  ## You must specify a time with a unit, for example '30s' or '2m'.
  ## Defaults to '30s'
  #keep_alive_timeout = '30s'

  ## Maximum number of times to retry before exiting. Defaults to unlimited (-1)
  #max_retry_count = 10

  ## Maximum wait time before retrying after a disconnection. Defaults to 5 minutes
  #max_retry_interval = '5m'

  ## Write a state file to {data_dir}/state.json that can be evaluated by external watchdog implementations.
  ## On Linux this also enables the systemd watchdog integration by using the systemd notify socket.
  ## Requires max_retry_count = -1 and keep_alive > 0
  ## Read more https://oss.rport.io/advanced/watchdog-integration/
  ## Disabled by default.
  #watchdog_integration = false

  ## Optionally set the 'Host' header. Defaults to the host found in the server url
  #hostname = "myvm1.lan"

  ## Other custom headers in the form "HeaderName: HeaderContent"
  #headers = ['User-Agent: test1', 'Authorization: Basic XXXXXX']
```

**Comment by thorstenkramm** [comment]
@Shivangraj Can you active the debug log level on the client to get more details?

**Comment by Shivangraj** [comment]
hey @thorstenkramm , here are the debug logs --

2023/02/08 01:32:31 debug: client: ping to 20.xx.xxx.241:80 succeeded within 68.394892ms
2023/02/08 01:33:09 debug: client: 621 bytes of monitoring measurements sent within 51.232µs
2023/02/08 01:34:09 debug: client: 621 bytes of monitoring measurements sent within 38.466µs
2023/02/08 01:34:23 debug: client: conn#3: [0/3]: Close (sent 7.15KB received 167KB)
2023/02/08 01:34:23 debug: client: conn#2: [0/3]: Close (sent 11.9KB received 280KB)
2023/02/08 01:34:23 debug: client: SSH Connection for monitoring set.
2023/02/08 01:34:23 error: client: Monitoring ended by context.Done
2023/02/08 01:34:23 debug: client: Monitoring stopped
2023/02/08 01:34:23 info: client: Disconnected
2023/02/08 01:34:23 error: client: Connection error: read tcp 10.xx.xxx.x01:43118->20.xx.xxx.241:80: read: connection reset by peer
2023/02/08 01:34:23 info: client: Retrying in 100ms...
2023/02/08 01:34:23 info: client: Trying to connect to ws://xxxxxxxxxx:80 ...
2023/02/08 01:34:23 debug: client: Handshaking...
2023/02/08 01:34:23 info: client: Server's full fingerprint xxxxxxxxxxxxxxxxxxxxxxxxxx
2023/02/08 01:34:23 info: client: Sending connection request.
2023/02/08 01:34:23 debug: client: Sending connection request with client details {"ID":"ce9570cxxxxxxxxafbab9632b5870","Name":"1143 Spring","SessionID":"75d23d2b-45bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"enabled":true}}}
2023/02/08 01:34:23 debug: client: Connection request has been answered successfully within 131.50621ms.
2023/02/08 01:34:23 error: client: Connection error: Local port 22876 already in use. (Attempt: 1 of infinite)
2023/02/08 01:34:23 info: client: Retrying in 200ms...
2023/02/08 01:34:24 info: client: Trying to connect to ws://xxxxxxxxxx:80 ...
2023/02/08 01:34:24 debug: client: Handshaking...
2023/02/08 01:34:24 info: client: Server's full fingerprint xxxxxxxxxxxxxxxxxxxxxxxxxx
2023/02/08 01:34:24 info: client: Sending connection request.
2023/02/08 01:47:28 debug: client: Sending connection request with client details {"ID":"ce9570cxxxxxxxxafbab9632b5870","Name":"1143 Spring","SessionID":"75d23d2b-45bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"enabled":true}}}
2023/02/08 01:34:24 debug: client: Connection request has been answered successfully within 72.025805ms.
2023/02/08 01:34:24 info: client: Connected to 20.xx.xxx.241:80 within 72.049996ms
2023/02/08 01:34:24 debug: client: SSH Connection for monitoring set.
2023/02/08 01:34:24 debug: client: Server has capabilities: {"ServerVersion":"0.9.5","MonitoringVersion":1}
2023/02/08 01:34:24 debug: client: Monitoring started
2023/02/08 01:34:24 debug: client: 624 bytes of monitoring measurements sent within 30.304µs
2023/02/08 01:34:39 debug: client: SSH Connection for monitoring set.
2023/02/08 01:34:39 debug: client: Monitoring stopped
2023/02/08 01:34:39 info: client: Disconnected
2023/02/08 01:34:39 error: client: Connection error: read tcp 10.xx.xxx.x01:52536->20.xx.xxx.241:80: read: connection reset by peer
2023/02/08 01:34:39 info: client: Retrying in 100ms...
2023/02/08 01:34:39 error: client: Monitoring ended by context.Done
2023/02/08 01:34:39 info: client: Trying to connect to ws://xxxxxxxxxx:80 ...
2023/02/08 01:34:40 debug: client: Handshaking...
2023/02/08 01:34:40 info: client: Server's full fingerprint xxxxxxxxxxxxxxxxxxxxxxxxxx
2023/02/08 01:34:40 info: client: Sending connection request.
2023/02/08 01:34:40 debug: client: Sending connection request with client details {"ID":"ce9570cxxxxxxxxafbab9632b5870","Name":"1143 Spring","SessionID":"75d23d2b-45bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"enabled":true}}}
2023/02/08 01:34:40 debug: client: Server has capabilities: {"ServerVersion":"0.9.5","MonitoringVersion":1}
2023/02/08 01:34:40 debug: client: Monitoring started
2023/02/08 01:34:40 debug: client: Connection request has been answered successfully within 82.603593ms.
2023/02/08 01:34:40 info: client: Connected to 20.xx.xxx.241:80 within 82.618035ms
2023/02/08 01:34:40 debug: client: SSH Connection for monitoring set.
2023/02/08 01:34:40 debug: client: Cannot send measurement. SSH connection missing. m.conn = nil
2023/02/08 01:35:31 debug: client: ping to 20.xx.xxx.241:80 succeeded within 68.203209ms
2023/02/08 01:35:40 debug: client: 621 bytes of monitoring measurements sent within 39.976µs
2023/02/08 01:36:40 debug: client: 622 bytes of monitoring measurements sent within 36.937µs
2023/02/08 01:37:40 debug: client: 621 bytes of monitoring measurements sent within 37.603µs
2023/02/08 01:38:31 debug: client: ping to 20.xx.xxx.241:80 succeeded within 115.620267ms
2023/02/08 01:38:40 debug: client: 622 bytes of monitoring measurements sent within 35.605µs
2023/02/08 01:38:46 debug: client: conn#4: [1/4]: Open
2023/02/08 01:39:40 debug: client: 623 bytes of monitoring measurements sent within 36.12µs
2023/02/08 01:40:40 debug: client: 623 bytes of monitoring measurements sent within 59.367µs
2023/02/08 01:41:31 debug: client: ping to 20.xx.xxx.241:80 succeeded within 68.152548ms
2023/02/08 01:41:40 debug: client: 622 bytes of monitoring measurements sent within 39.601µs
2023/02/08 01:42:40 debug: client: 621 bytes of monitoring measurements sent within 46.144µs
2023/02/08 01:43:40 debug: client: 622 bytes of monitoring measurements sent within 37.365µs
2023/02/08 01:44:31 debug: client: ping to 20.xx.xxx.241:80 succeeded within 68.558572ms
2023/02/08 01:44:40 debug: client: 622 bytes of monitoring measurements sent within 35.124µs
2023/02/08 01:45:40 debug: client: 622 bytes of monitoring measurements sent within 77.695µs
2023/02/08 01:46:40 debug: client: 622 bytes of monitoring measurements sent within 43.645µs
2023/02/08 01:47:27 debug: client: SSH Connection for monitoring set.
2023/02/08 01:47:27 debug: client: Monitoring stopped
2023/02/08 01:47:27 info: client: Disconnected
2023/02/08 01:47:27 error: client: Connection error: read tcp 10.xx.xxx.x01:55906->20.xx.xxx.241:80: read: connection reset by peer
2023/02/08 01:47:27 info: client: Retrying in 100ms...
2023/02/08 01:47:27 debug: client: conn#4: [0/4]: Close (sent 6.36KB received 17.8KB)
2023/02/08 01:47:27 error: client: Monitoring ended by context.Done
2023/02/08 01:47:27 info: client: Trying to connect to ws://xxxxxxxxxx:80 ...
2023/02/08 01:47:27 debug: client: Handshaking...
2023/02/08 01:47:27 info: client: Server's full fingerprint xxxxxxxxxxxxxxxxxxxxxxxxxx
2023/02/08 01:47:27 info: client: Sending connection request.
2023/02/08 01:47:27 debug: client: Sending connection request with client details {"ID":"ce9570cxxxxxxxxafbab9632b5870","Name":"1143 Spring","SessionID":"75d23d2b-45bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"enabled":true}}}
2023/02/08 01:47:28 debug: client: Connection request has been answered successfully within 230.739067ms.
2023/02/08 01:47:28 error: client: Connection error: Local port 22876 already in use. (Attempt: 1 of infinite)
2023/02/08 01:47:28 info: client: Retrying in 200ms...
2023/02/08 01:47:28 info: client: Trying to connect to ws://xxxxxxxxxx:80 ...
2023/02/08 01:47:28 debug: client: Handshaking...
2023/02/08 01:47:28 info: client: Server's full fingerprint xxxxxxxxxxxxxxxxxxxxxxxxxx
2023/02/08 01:47:28 info: client: Sending connection request.
2023/02/08 01:47:28 debug: client: Sending connection request with client details {"ID":"ce9570c56715165c6eafbab9632b5870","Name":"1143 Spring","SessionID":"75d23d2b-45bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"enabled":true}}}
2023/02/08 01:47:28 debug: client: Server has capabilities: {"ServerVersion":"0.9.5","MonitoringVersion":1}
2023/02/08 01:47:28 debug: client: Monitoring started
2023/02/08 01:47:28 debug: client: Connection request has been answered successfully within 72.069815ms.
2023/02/08 01:47:28 info: client: Connected to 20.xx.xxx.241:80 within 72.086928ms
2023/02/08 01:47:28 debug: client: SSH Connection for monitoring set.
2023/02/08 01:47:28 debug: client: 621 bytes of monitoring measurements sent within 39.288µs
2023/02/08 01:47:31 error: client: Failed to send keepalive (client to server ping): EOF
2023/02/08 01:47:31 debug: client: SSH Connection for monitoring set.
2023/02/08 01:47:31 debug: client: Monitoring stopped
2023/02/08 01:47:31 info: client: Disconnected
2023/02/08 01:47:31 error: client: Connection error: read tcp 10.xx.xxx.x01:35004->20.xx.xxx.241:80: read: connection reset by peer
2023/02/08 01:47:31 info: client: Retrying in 100ms...
2023/02/08 01:47:31 error: client: Monitoring ended by context.Done

**Comment by Shivangraj** [comment]
next day debug logs----

`2023/02/09 02:00:28 debug: client: ping to xx.1xx.xxx.xxx:80 succeeded within 50.075202ms
2023/02/09 02:01:17 debug: client: 622 bytes of monitoring measurements sent within 34.636µs
2023/02/09 02:02:17 debug: client: 622 bytes of monitoring measurements sent within 42.097µs
2023/02/09 02:03:17 debug: client: 623 bytes of monitoring measurements sent within 35.873µs
2023/02/09 02:03:28 debug: client: ping to xx.1xx.xxx.xxx:80 succeeded within 49.694625ms
2023/02/09 02:04:17 debug: client: 620 bytes of monitoring measurements sent within 40.053µs
2023/02/09 02:05:17 debug: client: 624 bytes of monitoring measurements sent within 39.828µs
2023/02/09 02:06:17 debug: client: 623 bytes of monitoring measurements sent within 42.601µs
2023/02/09 02:06:28 debug: client: ping to xx.1xx.xxx.xxx:80 succeeded within 50.231062ms
2023/02/09 02:07:17 debug: client: 622 bytes of monitoring measurements sent within 60.667µs
2023/02/09 02:08:17 debug: client: 623 bytes of monitoring measurements sent within 37.876µs
2023/02/09 02:09:17 debug: client: 623 bytes of monitoring measurements sent within 36.672µs
2023/02/09 02:09:29 debug: client: ping to xx.1xx.xxx.xxx:80 succeeded within 49.985131ms
2023/02/09 02:10:17 debug: client: 624 bytes of monitoring measurements sent within 39.031µs
2023/02/09 02:11:17 debug: client: 622 bytes of monitoring measurements sent within 36.079µs
2023/02/09 02:12:17 debug: client: 622 bytes of monitoring measurements sent within 38.079µs
2023/02/09 02:12:29 debug: client: ping to xx.1xx.xxx.xxx:80 succeeded within 50.433597ms
2023/02/09 02:13:17 debug: client: 623 bytes of monitoring measurements sent within 36.657µs
2023/02/09 02:14:17 debug: client: 622 bytes of monitoring measurements sent within 37.764µs
2023/02/09 02:15:17 debug: client: 622 bytes of monitoring measurements sent within 35.556µs
2023/02/09 02:15:29 debug: client: SSH Connection for monitoring set.
2023/02/09 02:15:29 debug: client: Monitoring stopped
2023/02/09 02:15:29 info: client: Disconnected
2023/02/09 02:15:29 error: client: Connection error: read tcp 10.xx.xxx.1x1:46248->xx.1xx.xxx.xxx:80: read: connection reset by peer
2023/02/09 02:15:29 info: client: Retrying in 100ms...
2023/02/09 02:15:29 error: client: Failed to send keepalive (client to server ping): EOF
2023/02/09 02:15:29 error: client: Monitoring ended by context.Done`

**Comment by thorstenkramm** [comment]
@Shivangraj  The message states the connection was closed. I'm sorry. But only with this message, it's not possible to investigate the reason for that.
