### ISSUE TITLE
Key base authentication for SSH tunnels

### ISSUE THREAD

**Issue by saitoh183** [cloudradar-monitoring/rport#917]
I wanted to know if there is a way to use SSH key when connecting instead of having to type the password once the tunnel is connected?

**Comment by thorstenkramm** [comment]
@saitoh183 This depends on the ssh client.
If you use on open-ssh client launched inside a terminal, the entire SSH environment is used. All your keys and the ssh agent is loaded, and key-based authentication will work.
Seems the [chrome extension](https://chrome.google.com/webstore/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd) to run the ssh connection inside the browser doesn't support key-based authentication. But I might be wrong.
